### ISSUE TITLE
Testergebnis Script

### ISSUE THREAD

**Issue by latzi0710** [SBorg2014/WLAN-Wetterstation#1]
Hi!

Hat etwas gedauert, schaut aber gut aus soweit. Anbei die Ausgabe (leider ohne Farbe ;) )

`Listening on [0.0.0.0] (family 2, port 80)
Connection from 10.0.0.35 37735 received!
[
  {
    "id": "javascript.0.Wetterstation.Innentemperatur",
    "val": 24.38
  },
  {
    "id": "javascript.0.Wetterstation.Aussentemperatur",
    "val": -1.5
  },
  {
    "id": "javascript.0.Wetterstation.Taupunkt",
    "val": -5.88
  },
  {
    "id": "javascript.0.Wetterstation.Chillfaktor",
    "val": -1.5
  },
  {
    "id": "javascript.0.Wetterstation.Innenfeuchtigkeit",
    "val": 38
  },
  {
    "id": "javascript.0.Wetterstation.Aussenfeuchtigkeit",
    "val": 72
  },
  {
    "id": "javascript.0.Wetterstation.Wind",
    "val": 0.32
  },
  {
    "id": "javascript.0.Wetterstation.Wind_max",
    "val": 1.77
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung",
    "val": 286
  }
]

Messwerteblock: 24.38 -1.50 -5.88 -1.50 38 72 .32 1.77 286

Temperatur Innen        : 24.38 °C
Temperatur Aussen       : -1.50 °C
Taupunkt                : -5.88 °C
Chill-Faktor            : -1.50 °C
Luftfeuchte Innen       : 38 %
Luftfeuchte Aussen      : 72 %
Windgeschwindkeit       : .32 km/h
max. Windgeschwindkeit  : 1.77 km/h
Windrichtung            : 286 °
Luftdruck absolut       : 983.81 hPa
Luftdruck relativ       : 1044.33 hPa
Regen aktuell           : 0 mm
Regen Tag               : 0 mm
Regen Woche             : .9 mm
Regen Monat             : .9 mm
Sonnenstrahlung         : 0.00 W/m²
UV-Index                : 0
Zeitstempel             : 28.12.2019 20:14:29

Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=24.38&javascript.0.Wetterstation.Aussentemperatur=-1.50&javascript.0.Wetterstation.Taupunkt=-5.88&javascript.0.Wetterstation.Chillfaktor=-1.50&javascript.0.Wetterstation.Innenfeuchtigkeit=38&javascript.0.Wetterstation.Aussenfeuchtigkeit=72&javascript.0.Wetterstation.Wind=.32&javascript.0.Wetterstation.Wind_max=1.77&javascript.0.Wetterstation.Windrichtung=286&prettyPrint

`

**Comment by SBorg2014** [comment]
Ich schließe den Issue mal, da es jetzt ja läuft. Bei Bedarf neuen erstellen ;-)
Projekt ist jetzt öffentlich für alle lesbar, WiKi (deswegen öffentlich, vorher kann man keines erstellen, außer man hat einen kostenpflichtigen GitHub-Account) habe ich mal angefangen...
