### ISSUE TITLE
Es fehlen in der Beschreibung für Grafana Plugins

### ISSUE THREAD

**Issue by fabiankrauss** [SBorg2014/WLAN-Wetterstation#10]
Hallo,

in der Beschreibung fürs Grafana Dashboard fehlen folgende Plugins:

farski-blendstat-panel
table-old

Danke für das schöne Dashboard!

**Comment by SBorg2014** [comment]
Danke 👍
Habe es nun ergänzt (ist mir gar nicht aufgefallen).
