### ISSUE TITLE
Credentials für Simple API-Adapter

### ISSUE THREAD

**Issue by unltdnetworx** [SBorg2014/WLAN-Wetterstation#11]
Verbesserungsvorschlag:
Hinzufügen von Benutzername und Kennwort des Simple API-Adapters um auch passwortgeschütze ioBroker Installationen befüttern zu können.

Der String zum Übertragen an ioBroker müsste dann nur um `&user=UsernameAusIobroker&pass=PasswordAusIobroker` ergänzt werden.

Bei der Gelegenheit könnte auch http/https variabel gestaltet werden.

**Comment by SBorg2014** [comment]
Nicht die schlechteste Idee ;-)
HTTP[S] ist dabei noch einfach umzusetzen, allerdings dürfte "nur um String..." schon etwas schwieriger werden. Ich weiß ad hoc nicht ob ich dann &user/&pass immer (auch leer) mitschicken kann/darf. Außerdem dürfen dann User + PW keine (oder ganz bestimmte) Sonderzeichen enthalten, da ich nicht, oder nur mit einem Riesenaufwand, escapen kann.
Ich schau aber mal und ist notiert 👍

**Comment by unltdnetworx** [comment]
Also User und PW können auch leer mitgeschickt werden, ein Standardwert für den Link, etwa `?user=&pass=` wäre also schon mal möglich.

**Comment by SBorg2014** [comment]
Zumindest ein Teilerfolg. Leider ist es dann doch etwas aufwändiger als zuerst gedacht, da sich die beiden Methoden von "set/setBulk" beim Simple-API Adapter unterscheiden, Mal schnell "suchen & ersetzen" geht leider nicht.

**Comment by SBorg2014** [comment]
Support mit V1.5.0 hinzugefügt.
