### ISSUE TITLE
Anbindung auch über RFLink möglich?

### ISSUE THREAD

**Issue by Grillbert** [SBorg2014/WLAN-Wetterstation#12]
Ich weiß es ist off-topic, aber vielleicht bist Du im Rahmen Deiner "Forschung" auch schon darüber gestolpert...

Ich würde mir gerne die Wetterstation als "Sonsor only" kaufen: https://www.conrad.de/de/p/eurochron-ec-3802394-kombi-sensor-1901197.html 
Um sie dann mit diesem Projekt: http://www.rflink.nl/blog2/devlist 
Über einen ESP32: https://youtu.be/oYfbEyzT-Gs 

Direkt MQTT Messages senden zu lassen (die dann über IOTStack in eine Influx-DB gespeist werden und mit Grafana visualisiert werden)...

Bisher habe ich davon noch genau NICHTS umgesetzt - aber vielleicht hast Du ja auch schon überlegt ob man direkt auf der Proprietären Schnittstelle zur "Basis" lauschen könnte ... evtl würde hier auch Niederschlag schneller angezeigt, denn als Regensensor für die Markiese wollte ich die Wetterdaten auch gerne nutzen.

Gruß,
  Gilbert

**Comment by SBorg2014** [comment]
Ja, bin ich, habe mir sogar schon einen Empfänger gekauft. Leider ist das nicht sooo einfach, denn du musst bei 868MHz schauen, und da wird der Support mehr als dünn. Da ich sowieso das Display ebenfalls nutze habe ich es erst mal nach hinten gestellt.

...und bei Markise kann ich dir gleich den Zahn ziehen, dass funktioniert nicht (und wird es auch nie). Bei den "üblichen" Masten ist ein Regen**mengen**sensor verbaut, kein echter Regensensor. Wg. der Konstruktion eine Menge zu messen, muss diese Menge auch erst mal zusammenkommen bis ein Impuls ausgelöst wird. Die Wippe löst IMO bei 30ml (ist aber nicht so wichtig wie viel nun genau) aus = dauert bei Nieselregen bis zu 15 Minuten, bei "normal" starkem Regen ca. 5 Minuten. Ist der Impuls erst mal da, dauert es weniger als 1 Sekunde vom Mast bis in den ioB oder what else. Die Verarbeitung ist also nicht das Problem ;)
Für die Markise benötigst du also einen echten Regensensor wie bspw, von Kemo oä. Beheizt, sonst bekommst du schon bei Tau einen Impuls, oder noch paar Stunden später obwohl es schon lange nicht mehr regnet, weil die Sensorfläche noch feucht ist...

LG
SBorg

**Comment by Grillbert** [comment]
Danke für das schnelle Reply.
Ich hatte parallel auch eine Anfrage an RFLink gestellt wie sie einschätzen ob dieses Modell unterstützt werden könnte.

Die haben auch sofort geantwortet und mir leider wenig Hoffnung gemacht. 

Dass die Untauglichkeit als regensensor hardwarebedingt ist ist auch ein guter Punkt - dann muss ich nochmal überlegen ob und wie ich das mache... Ich denke in die "Tau" Problematik würde ich nicht so schnell laufen - unsere Markise wird wohl eher erst ausgefahren wenn die Sonne schon scheint.... 
Ich probiere allerdings mit meinen "Smart Home" Gedöns so wenig wie möglich Stand-By Verbraucher ins Haus zu holen... und wenn ich mir für jeden Quatsch einen eigenen ESP32 ins WLAN hänge sammeln sich auch die verbrauchten Watts....  Vielleicht lässt sich ein ESP32 mit Regen über den Touch-Sensor aus dem Deep-SLeep holen, dann ginge es mit Batterie/Akku   :) 

Beste Grüße,
  Gilbert

**Comment by SBorg2014** [comment]
Ich hatte mir das Komplettset (gab es auch vor paar Tagen bei Voelkner) aus Mast + Display für ~110,- € geholt. Ist dann auch nicht so extrem viel teurer als Ersatzmast und weitere Hardware.
Ich hatte mir überlegt den Mast einfach umzubauen, also Elektronik raus + einen ESP rein. Würde auch ganz gut funktionieren, nur WLAN braucht einfach im Akkubetrieb zu viel Strom. Nehmen wir einen Nano mit 868MHz Sender im DeepSleep und auf der Gegenseite einen ESP oä. mit Empfänger....
Ich bastel zwar gern, aber das war mir dann doch irgendwann zu viel. Im IoBroker-Forum hatte ich dazu auch Bilder vom Innenleben gepostet.

Gruß
SBorg
