### ISSUE TITLE
LUX

### ISSUE THREAD

**Issue by 30er** [SBorg2014/WLAN-Wetterstation#13]
Servus
Zuerst mal danke für dieses mega Projekt! Tolle Arbeit!

Würde noch **LUX** aus zusätzlichen Datenpunkt vorschlagen.

Zur Umrechnung aus der Sonnenenergie hab ich folgende Beschreibung in den "froggit Wetterstation" Dokumenten gefunden:

```
Der Standardumrechnungsfaktor, basierend auf der Wellenlänge für helles
Sonnenlicht, beträgt 126,7 Lux / w/m2. Diese Variable kann von Photovoltaikexperten
basierend auf der interessierenden Lichtwellenlänge eingestellt werden, ist aber für die
meisten Besitzer von Wetterstationen für typische Anwendungen, wie z.B. die
Berechnung der Verdampfung und der Effizienz des Solarmoduls, genau.
```

Ich denke diese 126,7 solltest du als config hinterlegen, sodass diese bei bedarf angepasst werden kann.

LG und guten Rutsch

**Comment by SBorg2014** [comment]
Hi,
ich hatte mich ganz bewusst dagegen entschieden. Ich bin zwar kein Experte, aber wegen des benutzten Licht-Spektrums der Sensoren (Solar vs. Lux) kann man das nur bedingt umrechnen. Das stimmt nur für einen bestimmten Peak, danach driftet es ziemlich weit von der Realität ab. Sehe ich auch, denn ca. 2km von mir entfernt ist ein "echter" Luxmesser. Über den Tag verglichen liege ich um den Faktor +/- 15-fach daneben. Zu den recht ungenauen (eben Hobbyqualität) Sensoren noch eine weitaus weniger genaue Berechnung? Deswegen zeigt wohl auch weder Ecowitt noch Wunderground die Werte an. Würden sie sicherlich wenn es so einfach wäre ;)
Von daher habe ich eine Hardwareerweiterung geplant, die neben Luftgüte, Blitzsensor usw. dann auch einen echten Lux-Sensor hat.
Wer möchte kann sich ja ein Mini-Blockly bauen. Trigger bei Änderung auf die Solarenergie und dann eine einfache Aktualisierung auf den Datenpunkt "Lux" mit 'Wert der Solarenergie' * 126.7

Von  daher, sorry, eher nicht, außer mir liefert jemand wie es umzusetzen wäre mit plausiblen Werten als Ergebnis.

VG und ebenfalls einen guten Rutsch

**Comment by 30er** [comment]
danke für die rasche antwort.
Habe mir bereits einen trigger geschrieben ;)
LG
