### ISSUE TITLE
Datenpunkte 'Temperatur.xx.Min_24h'

### ISSUE THREAD

**Issue by Rene5555** [SBorg2014/WLAN-Wetterstation#14]
Zuerst Danke für das tolle Dashboard. In einem Panel fehlen mir allerdings die Werte für "Statistik.Temperatur.Außen.Min_24h" und "Statistik.Temperatur.Außen.Max_24h". Die konnte ich bisher nirgends finden. Muss ich da noch etwas hinzubasteln?

**Comment by SBorg2014** [comment]
Hi, ja, wenn du es als reinen Zahlenwert möchtest. Ich schau nur auf die Legende im Graphen, da steht es ebenfalls. Ist auch etwas der Historie geschuldet, denn das Dashboard kam gleich nach dem Skript (welches die Min-/Maxwerte nicht liefert, da sie so von der Station nicht zur Verfügung gestellt werden und ich dafür dann eine Datenbank anlegen müsste).
Mittlerweile werden die Daten aber auch vom Statistik-Addon generiert und dann, sofern man es aktiviert, ggf. in die Influx geschrieben. Eleganter als dies im Skript per extra DB zu realisieren wie ich finde, gerade weil man wg. des Dashboards sowieso zwingend eine Influx laufen lassen muss.

**Comment by Rene5555** [comment]
Danke für die fixe Antwort. Ja, Influx läuft und macht soweit alles. Meinst du das 'Wetterstation-Statistik' von dir? Das läuft auch.

**Comment by SBorg2014** [comment]
Ja, beim Statistik gibt es "Vortag", da ist max/min enthalten. Was nicht geht (bzw. vorliegt) ist "Jetzt - 24 Stunden". Da müsste ich (wenn die Daten bspw. alle 30 Sekunden kommen) rund 3.000 Datensätze alle 30 Sekunden abfragen und auswerten. Wäre auf einem RaspberryPi schon fast der Overkill. Ich habe es noch nie gemacht/ausprobiert, aber da wäre eine Abfrage direkt per bash in Influx ev. möglich (und auch schnell).
Forum ist halt etwas komfortabler als "hier" und es lesen ggf. mehr Leute gerade wg. der Suche. So brauche ich ev. nicht alles zig mal erklären ;-)
Wenn der issue mal geschlossen ist versinkt es auch allmählich in der Vergessenheit.

**Comment by Rene5555** [comment]
Nochmals Danke, das mit der Überforderung sehe ich ein. Bash in influx - da tue ich mich schwer bzw. krieg ich so nicht hin. Am besten, den Issue schnell schließen. Ich hab eben erst den gesamten Thread gefunden und durch gelesen. Also ab ins Forum und hier weitermachen.

**Comment by SBorg2014** [comment]
Bzgl. bash + influx schau ich mal bei Gelegenheit, ist ev. auch für die Anderen interessant. Ich schließe hier dann morgen ;-)
