### ISSUE TITLE
Probleme bei installation in QNAP Docker

### ISSUE THREAD

**Issue by bertl83** [SBorg2014/WLAN-Wetterstation#15]
Sorry erst mal das ich hier n Issue aufmache.
Aber ich hoffe du kannst mir helfen.
Ich hab auf einer QNAP in der Containerstation n Docker mit iobroker laufen.
Ich geh nun per Putty auf die QNAP und von dort mit docker exec -i -t iobroker-1 bash in den Docker.
Per Host Share hab ich ein Verzeichnis im Docker zugänglich den ich per FileStation mit den nötigen Files (conf sh js usw) versorge.
Wenn ich nun per (sudo) ./wetterstation.sh --debug starte, bekomm ich nur:

root@iobroker:/opt/iobroker/transfer# sudo ./wetterstation.sh
/opt/iobroker/transfer/wetterstation.conf: line 4: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 7: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 10: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 13: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 16: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 19: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 23: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 26: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 29: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 32: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 35: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 40: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 42: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 56: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 58: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 59: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 60: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 67: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 70: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 73: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 76: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 79: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 82: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 83: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 84: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 87: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 90: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 93: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 96: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 100: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 104: $'\r': command not found
/opt/iobroker/transfer/wetterstation.conf: line 105: $'\r': command not found
")syntax error: invalid arithmetic operator (error token is "
: integer expression expectedstation.sub: line 577: [: 30
 * 6 + ANZAHL_DP100 * 4 : syntax error: invalid arithmetic operator (error token * 6 + ANZAHL_DP100 * 4 ")

 ist ungültig. Bitte die Einagbe in wetterstation.conf  korrigieren

root@iobroker:/opt/iobroker/transfer#

Daten kommen von der Wetterstation aber an, und das Config file hab ich auch entsprechend angepasst.
Wo könnte hier der Fehler liegen? Ich muss sagen ich bin bei Linux und auch Dockern ziemlich neu, wenn auch EDV technisch sicher kein Depp :)

**Comment by bertl83** [comment]
ich glaub ich hab den fehler. Hatte die conf davor mit Notepad++ geändert und gespeichert

**Comment by SBorg2014** [comment]
Jepp, "\r" deutet auf ein "Carriage Return / CR" hin, dass mag Linux nicht. Bei notepad++ als "Unix (LF)" speichern oder dann in Linux zB. "dos2unix" zum konvertieren nutzen ;-)

**Comment by bertl83** [comment]
@SBorg2014 
jetzt hät ich noch ein zweites "Problem" wo ich nicht drauf komm:
In der Conf und der Station selbst hab ich ein Polling von 30 sek eingestellt.
beim NC auf meinen Port 1088 bekomm ich die Daten:

root@iobroker:/opt/iobroker/transfer# nc -lv -p 1088
listening on [any] 1088 ...
connect to [192.168.2.49] from Wetterstation.fritz.box [192.168.2.41] 2641
GET /weatherstation/updateweatherstation.php?ID=ZuHause&PASSWORD=1136
&indoortempf=72.9&tempf=33.4&dewptf=31.1&windchillf=33.4&indoorhumidity=29&humidity=91&windspeedmph=0.0
&windgustmph=0.0&winddir=88&absbaromin=28.482&baromin=28.482&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.000
&monthlyrainin=0.059&yearlyrainin=0.059&solarradiation=0.00&UV=0&dateutc=2021-01-18%2005:20:36
&softwaretype=EasyWeatherV1.5.6&action=updateraw&realtime=1&rtfreq=5 HTTP/1.0
Host: 192.168.2.49
Accept:*/*
Connection: Close

Wenn ich dann die .sh starte bekomm ich quasi sofort:

root@iobroker:/opt/iobroker/transfer# ./wetterstation.sh --debug
iobroker [192.168.2.49] 8087 (?) open
listening on [any] 1088 ...
no connection : Connection timed out

Debug VAR:
Installationsverzeichnis: /opt/iobroker/transfer
IPP: 192.168.2.49:8087  WS_PORT: 1088           WS_POLL: 30             PRE_DP: javascript.0.Wetterstation
WEB: HTTP               WS_PROT: Wunderground   DP50/100: 0 | 0
Script-Version: V2.0.0  Config-Version: V2.0.0  Sub-Version: V2.0.0

Kommunikationsfehler! Stimmt die WS_ID in der Konfiguration mit der der WS View-App überein?

Wartet der einfach zu wenig lang? Aber wo wäre das noch zu ändern?

**Comment by SBorg2014** [comment]
Was mich zuerst "stört" ist eigentlich **iobroker [192.168.2.49] 8087 (?) open** (siehe auch [Wiki](https://github.com/SBorg2014/WLAN-Wetterstation/wiki/FAQ---Troubleshooting) )
Hier kann er keine Verbindung zum ioB aufbauen. Die netcat-Versionen unterscheiden sich in den Parametern, gerade bzgl. des Timeouts. Schadet nix die "größere" Version zu installieren. Du kannst zwar auch den Timeout vergrößern, aber er wartet sowieso zwei mal das Pollintervall ab, um Daten zu bekommen. Es funktioniert aber wahrscheinlich eh mit der anderen nc-Version ;-)

**Comment by bertl83** [comment]
NC sollte aktuell sein (netcat is already the newest version (1.10-41.1).)
wenn ich die Timeouts hochsetze läuft alles sauber durch, und kommt auch im IO an, zumindest seh ich die gelesenen Werte in den Objekten.
Aber du hast recht, hab nun [sudo] apt-get install netcat-openbsd gemacht und jetzt hauts auch mit den 1 sek Timeout hin.
Vielen Dank, dann mach ich das hier zu.
