### ISSUE TITLE
Unplausible Werte aus Wetterstation

### ISSUE THREAD

**Issue by FabianEKS** [SBorg2014/WLAN-Wetterstation#16]
Hallo,

zunächst einmal Vielen Dank für die Spitzenanleitung und die "WLAN-Wetterstation". Die Installation hat super geklappt und ich bekomme endlich alle Werte aus meiner Wetterstation (Renkforce WH2600). Womit ich aktuell noch ein wenig kämpfe ist das OpenSense-Skript. Das Anlegen der Werte/Sensoren etc. funktioniert soweit. Nur die Einbindung des Skriptes erzeugt bei mir aktuell noch ein paar Fragezeichen. Das Problem hier liegt vermutlich zwischen den Ohren ;). Aber nochmal: Auf genau diese "WLAN-Wetterstation" habe ich gewartet und bin darüber höchst erfreut.

Nun zu meinem eigentlichen Problem, weswegen ich hier poste:
Die WLAN-Wetterstation läugt nun seit mehreren Tagen, so dass ich inzwischen ganz passable Verläufe angezeigt bekomme. Was mir allerdings aufgefallen ist, dass zu manchen Zeiten die Werte ins Bodenlose fallen. Durch die automatische Skalierung werden dadurch die "normalen" Verläufe nicht mehr wirklich erkennbar. Ich habe versucht durch das Setzen eines "Min-values" im Objekt einen Wert <0 zu verhindern, doch aus irgendeinem Grund funktioniert das nicht.
![grafik](https://user-images.githubusercontent.com/72298450/110522341-13b52d80-8111-11eb-9221-7a81fec2ad44.png)

Nun könnte ich zwar die Skalen der Diagramme manuell bei 0 begrenzen, doch eine Auswertung eines Min/Max/Mittelwertes der Werte über einen bestimmten Zeitraum liefert aufgrund der Extremwerte falsche Werte.

Woran könnte das liegen? Die Wetterstation hat einen Innen- einen Außensensor. Beide sind über Funk mit der Basisstation verbunden. Die Extremwerte treten aber nur bei Werten der Außenstation auf (s. Screenshot unten). Kann das an der Verbindung des Außensensors liegen, d.h. keine Verbindung = Extremwert? Wie ließe sich solch ein Extremwert verhindern?

Über eine Einschätzung oder Anregung deiner-/eurerseits wäre ich dankbar.

Gruß, Fabian

![grafik](https://user-images.githubusercontent.com/72298450/110522807-9ccc6480-8111-11eb-9c4f-c625777447f3.png)

**Comment by SBorg2014** [comment]
Hi,
nö, die Min-/Max "Begrenzung" im ioB funktioniert da nicht, da sie nicht für eine Begrenzung der Werte gedacht ist. Für OpenSense wäre es da auch schon zu spät, denn dass Skript schickt die Daten direkt an OpenSense.
Ziel müsste es sein den Grund für die "Ausreißer" zu finden. Es scheint ja auch durchaus mal einen Tag zu funktionieren.
Was aber schon mal sehr merkwürdig ist, sind die Extreme (auch über einen längeren Zeitraum). Ein reines Verbindungsproblem kann es nicht sein. Dann kommt kein Datenstring und das Skript macht einfach gar nichts. Die Werte müssen also so schon von dem Wettermast/Display kommen.
Nachts scheint es auch häufiger aufzutreten (=[falls vorhanden] keine Solarunterstützung?). Ev. Batterien?

**Comment by FabianEKS** [comment]
Grüß dich,

Danke für deine Rückmeldung.

Kurz zur Batterie:
Es werden generell Batterien verwendet, die über das SOlarpanel geladen werden. Laut WebInterface sind die Batterien für die Außenstation i.O.:
![grafik](https://user-images.githubusercontent.com/72298450/110767346-7401b780-8256-11eb-8a77-daf22283b140.png)

Das ist alles wirklich merkwürdig. Warum ich auf das Skript kam ist nur dem Umstand geschuldet, dass vor der Umstellung solche Extremwerte nicht auftraten. Eine weitere Merkwürdigkeit ist mir gestern abend noch aufgefallen: Die Regenmenge des Tages funktioniert reibungslos. Dieser Wert kommt auch vom Außensensor:
![grafik](https://user-images.githubusercontent.com/72298450/110767589-b3c89f00-8256-11eb-85bc-e2166a0f8fa9.png)

Kann das evtl. daran liegen, dass die Werte alle 10s von der Wetterstation aktualisiert werden und das Skript die Daten alle 16s holt? Kommt es hierbei evtl. zu einem timing-Problem (dagegen spricht aus meiner Sicht aber die länger andauernden Extremwerte).

Kurz zur Info: Die angehängten Screenshots haben noch nicht smit OpenSense zu tun (Das Skript habe ich noch gar nicht eingebunden), sondern sind die Daten die über Lovelace angezeigt werden (Werte aus der SQL-Datenbank). Bei Grafana sieht es nebenbei genauso aus, d.h. Extremwerte vorhanden.

Hmm...Könnte es vielleicht mit den beiden parallel laufenden Datenbanken InfluxDB und SQL zusammenhängen?

Zu einem Zeitpunkt konnte ich die Extremwerte auch direkt in den Objekten beobachten.

Alles merkwürdig.

Danke für deine Unterstützung.

Gruß, Fabian

**Comment by SBorg2014** [comment]
Zumindest senden die bisherigen Stationen ~30 Sekunden. Allerdings war das nur bei den ersten Versionen von belang. Jetzt ist es egal wann die Daten kommen, nur wird halt dann 2x die Pollzeit gewartet, bis es als fehlendes Paket gewertet wird ("Kommunikationsfehler"). Später wird daraus die Solarenergie berechnet, da man hier die Leistung über eine Zeitspanne braucht.

Allgemeines Timing-Problem möchte ich eigentlich ausschließen. Erklärt nicht warum es mal einen ganzen Tag läuft, mal nur eine Spitze hat oder mal eine ganze Zeitspanne nicht geht. Außerdem käme da auch keine Temperatur wie -5.800°C zu Stande, sondern zB. "Null" da kein Messwert vorliegt. 

Ich habe nur eine InfluxDB laufen und könnte dann an der SQL liegen, dürfte aber nicht und mag ich auch nicht so Recht glauben. Warum sollten dann auch gerade die Werte vom Innensensor stimmen?

Auf was für einem System läuft denn das Skript? So merkwürdige Fehler können auftreten wenn der RAM zur Neige geht, oder gerade beim PI in den SWAP auf der SD-Karte ausgelagert werden muss.

**Comment by FabianEKS** [comment]
Deiner Argumentation kann ich folgen, d.h. timing und influx/SQL-Kollision unwahrscheinlich.

Das Skript läuft auf einem Raspi4 mit 4GB RAM. Das sollte ausreichen, oder?
![grafik](https://user-images.githubusercontent.com/72298450/110942808-9e2ca580-833a-11eb-9dcf-03f557432144.png)

Es läuft noch der Adapter RPI, der mir folgende Daten anzeigt:
![grafik](https://user-images.githubusercontent.com/72298450/110942962-dd5af680-833a-11eb-8daf-28e9acfe286e.png)

Ich werde diese Daten auch mal in der DB speichern. Mal sehen ob sich die Extremwerte mit RPI-Extremwerten überschneiden.

Z. Info: Seit fast 3 Tagen ist Ruhe mit Extremwerten...hm. Ich werde das weiter beobachten.

**Comment by Ilovegym66** [comment]
Auf der Übersicht oben steht "Indoor bat low" das könnte auch dazu beitragen, wenn der Empfänger da die Daten nicht richtig speichert ( Setzt ja vom 868Mhz Funk auf Wifi um ) und da dann ausreisst...

**Comment by FabianEKS** [comment]
@Ilovegym66 : Danke für deine Unterstützung.

Meiner Ansicht nach kommt der Zustand "Indoor Bat low" durch die verwendeten Akkus. Der Zustand ist schon seit 2 Jahren unverändert auf "low" ohne dass es zu einem Signalverlust kam. Zudem betrifft dieses "Extremwert-Thema" nur die Außensensoren. Ich versuch das noch weiter einzugrenzen.

**Comment by Ilovegym66** [comment]
Hi, ah, ok, aber kann gut sein, dass die Akkus ab und zu mal zusammenbrechen.. und dann sowas rauskommt...
Ich hab gerade n ganz anderes Problem.. mein Regentrichter ist UFO-Like beim Sturm davongesegelt.. :D 
dabei war der übern Jahr drauf und mit Sicherheit fest.. 
Hoffe, du findest den Fehler.. ist schon ärgerlich. Denke nicht, dass es am Script liegt, das wird von sovielen Leuten eingesetzt, das wäre aufgefallen.
Daher schieb ich das mal auf die Hardware...

**Comment by FabianEKS** [comment]
Ja, ich beobachte es weiterhin und versuche den Fehler weiter einzugrenzen. Ich melde mich auf jeden Fall nochmal wenn ich die nächste Erkenntnis gewonnen habe (oder noch eine Frage in Richtung Script ;)  ).

Danke für eure Unterstützung.

**Comment by SBorg2014** [comment]
>  mein Regentrichter ist UFO-Like beim Sturm davongesegelt.. 

Upsi, muss ich MUFON kontaktieren? 👽


Logge bitte mal deinen freien RAM mit. "~630MB frei" hört sich nach mehr an als es tatsächlich ist. Das Skript selbst braucht zwar recht wenig, wenn aber der ioB den bis fast zum Anschlag voll ballert kann es eng werden. Bei mir schwankt das bspw. um bis zu 2GB, je nach dem welcher Adapter gerade was macht.
...oder falls vorhanden: lagere es mal versuchsweise auf einen anderen Rechner/PI/VM... aus.

**Comment by FabianEKS** [comment]
![grafik](https://user-images.githubusercontent.com/72298450/110965154-384d1780-8354-11eb-8517-81572bbd3db8.png)
Schon eingerichtet.

Die Werte habe ich ehrlich gesagt noch nie wirklich hinterfragt bzgl. des Mem. Im Reiter "Instanzen" wird mir folgendes angezeigt:
![grafik](https://user-images.githubusercontent.com/72298450/110965489-882bde80-8354-11eb-8cbd-a577d31e52dc.png)

Hier ist es deutlich über den erwähnten 630MB und kommt in die von dir genannten Regionen von >2GB. Was ist nun der richtige Wert? Mem_Available oder Mem_free?

![grafik](https://user-images.githubusercontent.com/72298450/110965877-f4a6dd80-8354-11eb-8e7f-2ef5747348ae.png)
Was meinst du mit "es", das Skript? Ich glaube ehrlich gesagt nicht, dass die "Mem"-Größe etwas mit dem Skript zu tun hat, da es (zumindest aus der Erinnerung meine ich das) schon immer in diesen Größenordnungen angezeigt wurde. Der Grund hierfür müsste woanders liegen. Was mir aufgefallen ist, dass ich angeblich 334 Adapter installiert habe:
![grafik](https://user-images.githubusercontent.com/72298450/110966458-8ca4c700-8355-11eb-99c0-209cf9d97cab.png)
Habt ihr hier eine ähnlich hohe Zahl? Laufen tun aber nur 11 Instanzen (das passt).

**Comment by SBorg2014** [comment]
Die Anzeige per "Info" zeigt dir nur was der ioB so braucht,
Die Anzeige per Adapter was dein PI so hat. Available = was dein PI so nach dem laden des Kernels, Treiber, GUI etc. noch frei hat. Davon geht nun bspw. SQL, Influx, Grafana etc. pp. ab = Mem_free

...und ja, das Skript, falls du halt noch was an Hardware hast. Die Station ist es sicherlich nicht, das Skript läuft auch, bleibt eigentlich nur noch der Rechner an sich (oder Software darauf die stört).

Die Adapter-Anzahl ist nur die verfügbare Anzahl an Adaptern. Bei mir sind es 402 da ich im "latest" unterwegs bin, du wohl im "stable" ;-)

**Comment by FabianEKS** [comment]
Danke für die Erklärung...endlich Licht im Dunkel :)

Ich habe nun SQL abgschaltet. Nachdem alle Adapter/Skripte auch mit InfluxDB laufen, kann ich mir diese sinnlose Speicherbelastung sparen. Und, siehe da, der Speicher wird frei:
![grafik](https://user-images.githubusercontent.com/72298450/111035451-efac6180-841a-11eb-938b-d456848b5317.png)
![grafik](https://user-images.githubusercontent.com/72298450/111035464-0783e580-841b-11eb-8aed-4ea22a30b8d0.png)

Das heißt aber auch, dass SQL ca. 2GB Speicher belegt hat...Irre. Das hätte ich nicht gedacht. Wird die komplette SQL-DB immer in den Speicher geladen? Ist das auch bei InfluxDB so? Falls ja, werde ich mir überlegen das Speicherintervall (aktuell 1 Jahr) zu verkürzen.

**Comment by SBorg2014** [comment]
Ob es die ganze DB ist kann ich dir nicht sagen, aber aus Performance Gründen zumindest einiges. SQL ist auch eher was für zB, die Filmsammlung, da du hier nach Genre sortieren/suchen willst, oder nach Schauspieler, oder, oder..., du halt viele Felder pro Datensatz hast.
Influx ist hier wesentlich besser und schlanker, da sie Timeline basierend ist. Du hast eine Messreihe und einen Zeitstempel dazu. Denn egal was du von der DB im Smarthome willst, es wird immer zu einem bestimmten Zeitpunkt/-raum sein: wann hat es zuletzt geregnet, wie war gestern die Temperatur um x:xx Uhr, regnet es aktuell, Sonnenscheindauer letzte Woche...
Die Daten sind hier auch auf einer Zeitachse. Du hast immer einen Zeitpunkt und einen Messwert.

...und müsste ich einen Tipp abgeben, würde ich stark darauf setzen, dass deine Ausreißer nun Geschichte sind ;-)
Bei Influx kannst du auch ruhig ein Jahr oder länger die Daten vorhalten, hier wird nur die Datenbank auf dem Speichermedium größer. Der Speicherbedarf im RAM nimmt hierbei nicht zu.
