### ISSUE TITLE
DP1500 Wi-Fi Wetterserver USB-Dongle Support?

### ISSUE THREAD

**Issue by Coalado** [SBorg2014/WLAN-Wetterstation#17]
Is the DP1500 Wi-Fi Wetterserver USB-Dongle (https://www.froggit.de/product_info.php?info=p412_dp1500-wi-fi-wetterserver-usb-dongle-inkl--1-x-dp50---wh31a-thermo-hygrometer-funksensor.html)

Supported? I'd like to use the  1 x DP1500 + several Dp100 moisture sensors and connect them to iobroker. 

However, in the README, only HP1000SE Pro, WH3000 SE, WH4000 SE are listed.

**Comment by SBorg2014** [comment]
Hi, sorry, but that won't work. It's designed as a weather station and needs some values from eg WH3000 SE. If they not present, the script stops working.
I think a solution with ESPEasy or ESPhome with a moisture sensor is here better.

**Comment by Coalado** [comment]
Mit ESP+Feuchtesensor ist die Hardware immer viel Bastelei -  vor allem weil sie ja möglichst stromsparend und Wasserdicht sein soll. 

Deswegen haben mich die DP100 angelacht. 

Mit einem solchen Set (HP1000SE) sollte es dann aber klappen, oder?

https://www.froggit.de/product_info.php?info=p442_hp1000se-pro-wi-fi-internet-funkwetterstation---1-x-dp100-mehrkanal-bodenfeuchte-funksensor.html&gclid=Cj0KCQjwi7yCBhDJARIsAMWFScMtPTVr0wUgZwMeBmwnks3Jlz1jZ1Tn_eiaTFpn1Wei_aA0Gz13Jc8aAn0TEALw_wcB


In der Readme steht:
"Zusatzsensoren (mittels Station oder Gateway DP1500[...]bis zu 8 Stück DP100[...] Bodenfeuchte-Sensoren"

Wie ist denn das dann gemeint? Da wird das DP1500 Gateway ja genannt.

**Comment by SBorg2014** [comment]
Es gibt nur ein paar "Displays" (um die geht es dabei) die auch ein paar Zusatzsensoren können. Für den Vollausbau oder für bestimmte (zB. Wasserleckage) braucht man unbedingt das Gateway. Dabei wird vom Skript alles unterstützt:

- nur Display
- nur Gateway
- beides zusammen

Damit das Skript aber funktioniert braucht man unbedingt auch den Wettermast/Außeneinheit. Dann kann man frei wählen ob/oder was an Zusatzsensoren, welches Display (oder eben auch ohne, dann aber mit Gateway) und ggf. Gateway (dann abhängig vom Display und den Zusatzsensoren).

Wenn du kein Display möchtest kannst du auch bspw. (https://www.froggit.de/product_info.php?info=p420_dp1500-wi-fi-wetterserver-usb-dongle-inkl--1-x-dp50-wh31a---wh3000se-all-in-one-aussensensor.html) nehmen.

Willst du zB. auch einen Blitzsensor, kommst du um das Gateway nicht herum, da es aktuell meines Wissens nach kein Display gibt welches den DP60 unterstützt. Das Gateway kann immer alleine oder zusammen mit dem Display betrieben werden. Nur deine Eingangsfrage geht nicht: Gateway und Zusatzsensoren alleine. Da muss der Wettermast mit dazu (nicht technisch, aber ohne ist einfach beim Skript nie vorgesehen gewesen) ;-)
