### ISSUE TITLE
Daten werden übertragen, aber nicht in iobroker übergeben

### ISSUE THREAD

**Issue by hopedotz** [SBorg2014/WLAN-Wetterstation#18]
Hi und Danke für den Adapter! Hab das soweit jetzt zum laufen gebracht. Allerdings werden von meiner Station folgende Daten übergeben:

`PASSKEY=67739703DBA3AE1C297E2E2A5082776D&stationtype=WH2650A_V1.6.3&dateutc=2021-04-07+19:43:39&tempinf=75.6&humidityin=31&baromrelin=31.379&baromabsin=28.815&tempf=32.0&humidity=92&winddir=210&windspeedmph=0.89&windgustmph=3.36&maxdailygust=13.65&solarradiation=0.00&uv=0&rainratein=0.000&eventrainin=0.000&hourlyrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.000&yearlyrainin=0.000&totalrainin=0.000&wh65batt=0&wh25batt=0&freq=868M&model=WH2650`

Diese werden aber weder in der Konsole beim debug angezeigt, noch in die Datenpunkte in iobroker übertragen. Mach ich was falsch oder.... :)

**Comment by SBorg2014** [comment]
Hi,
ich vermute, wenn sonst alles stimmt, lediglich eine "falsche" netcat-Version. Steht bei dir ganz zu Beginn der debug-Ausgabe "open" oder "succeded" bei der Verbindung zum ioB?
Falls "open", dann schau mal bitte unter https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/2457 und teile mir hier das Ergebnis mit (Lösung siehe dann WiKi), dann kann ich für die nächste Version die Prüfung mit einbauen und es ggf. automatisch fixen lassen 😀
