### ISSUE TITLE
Debian 10 - Start wetterstation.sh hängt, falls netcat-traditional installiert

### ISSUE THREAD

**Issue by cvbkf** [SBorg2014/WLAN-Wetterstation#19]
Hi,

danke für die tolle Software - ich habe gestern das ganze auf einer Debian 10 VM installiert, und dabei festgestellt, dass das Shell-Skript bei der Prüfung auf netcat-openbsd hängen bleibt, wenn das Paket "netcat-traditional" installiert ist (z.b. auch parallel zur openbsd-Variante). Nach Entfernen des Paketes ging es dann sofort. Das könnte vielleicht noch in die checks eingebaut werden.

**Comment by SBorg2014** [comment]
Hi, danke für den Hinweis. Augenscheinlich habe ich jetzt zwar so keinen Fehler entdeckt, ausprobieren kann ich es aktuell aber leider auch nicht. Die letzte Hitzewelle tat meiner SSD wohl nicht gut.
Ich schaue es mir aber auf jeden Fall vor der nächsten Version (aktuell + "WH45-Sensor") genauer an 🙂

**Comment by Vodochnik** [comment]
Das kann ich bestätigen. Bei mir unter Raspbian.

**Comment by Vodochnik** [comment]
if [[ $(sudo update-alternatives --config nc|grep "Nichts zu konfigurieren.") ]]; then
*ggg* nicht jeder hat seine Box auf Deutsch laufen)

Das Kommando verursacht bei mir folgende Ausgabe gefolgt von einer Eingabeaufforderung, die dann vom Script unterdrückt wird: 

root@raspberrypi:~# sudo update-alternatives --config nc
There are 2 choices for the alternative nc (providing /bin/nc).

  Selection    Path                 Priority   Status
------------------------------------------------------------
* 0            /bin/nc.openbsd       50        auto mode
  1            /bin/nc.openbsd       50        manual mode
  2            /bin/nc.traditional   10        manual mode

Press <enter> to keep the current choice[*], or type selection number:

Zwei mal Enter drücken hilft, aber man muss erst draufkommen)

**Comment by SBorg2014** [comment]
Nicht nur "nicht deutsch", wenn beide installiert sind hängt er dann. Habe aber schon eine funktionierende Möglichkeit gefunden, die auch sprachunabhängig ist: **sudo update-alternatives --query nc|grep Value**
Liefert je nach aktivierter Version _Value: /bin/nc.openbsd_ oder _Value: /bin/nc.traditional_ ,auch zuverlässig wenn nur eine Version installiert ist 😁
Danke fürs Feedback!
