### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by dan1-de** [SBorg2014/WLAN-Wetterstation#20]
Hi @SBorg2014, 

vielen Dank für dein Script. Es funktioniert wunderbar mit meiner CHILITEC CTW-902.

Um dein Script in meine bestehende Docker Umgebung einzubinden, habe ich ein docker-compose file geschrieben. 

Wenn du Lust hast, kannst du es gerne in die Anleitung mit aufnehmen, da es dem einen oder anderen bestimmt weiterhelfen kann.

Hier eine kurze Beschreibung:

Die 3 Dateien (wetterstation.conf, wetterstation.sh,wetterstation.sub) in einen Ordner mit dem Namen "wetterstation" im gleichen Pfad wie das "docker-compose.yml" file ablegen und entsprechend der eigenen Konfiguration bearbeiten. Dieser Ordner wird dann im Docker Compose eingebunden und unter /opt/wetterstation im Linux Container gemountet.

Zum Starten, einfach das Dockerfile im Anhang mit dem Befehl "docker-compose up" im gleichen Ordner starten.
Github erlaubt den Dateityp ".yml" nicht. Daher muss die hier hochgeladene Datei von "docker-compose.txt" in "docker-compose.yml" umbenannt werden.

Falls der Port in der "wetterstation.conf" angepasst wurde, müssen auch die Ports im "docker-compose.yml" angepasst werden.

[docker-compose.txt](https://github.com/SBorg2014/WLAN-Wetterstation/files/6803297/docker-compose.txt)

Viele Grüße
Daniel

**Comment by SBorg2014** [comment]
Hallo Daniel,
sehr gerne, und besten Dank im Namen der Docker-User 😊

Liebe Grüße
SBorg2014
