### ISSUE TITLE
openSenseMap

### ISSUE THREAD

**Issue by AlexanderSch90** [SBorg2014/WLAN-Wetterstation#21]
Hey, soweit ich das sehe funktioniert die Anlage der "senseBox" in einen vorhandenen Account nicht. Das Skript meldet das erfolgreiche einloggen und die erfolgreiche anlage, jedoch ist auf der Website die SenseBox nicht aufrufbar sodass id und token nicht kopiert werden können. Was benötigst du zum debuggen oder kannst du das selbst für dich einmal testen?

**Comment by SBorg2014** [comment]
Hi, eben getestet, funktioniert (noch; es könnte sich ja zwischenzeitlich was an der API geändert haben). Die Methoden sind auch identisch, es wird also nicht nach Neu-User/bestehender User unterschieden. Lediglich bei Neu-User wird zusätzlich vorher der Account angelegt, danach ist das weitere Prozedere identisch.
Ich weiß nicht ob es über das Web-Frontend identisch ist, bei der benutzen API sind aber keine Leer- oder Sonderzeichen im Usernamen/Passwort erlaubt.

Pauschal könntest du aber die Sensebox auch im Frontend anlegen und den Punkt dann im Skript überspringen, wenn es sonst nicht funktioniert (Einträge in der conf nicht vergessen). Nur die Sensoren sollte das Skript anlegen, denn das ist Fleißarbeit...

**Comment by AlexanderSch90** [comment]
Okay ich wollte nur sichergehen, ob es grundsätzlich funktioniert. Ich habe es nun manuell angepasst. Kann also geschlossen werden...

Noch ein Hinweis: Wenn man sich trotz schon eingetragenen User dazu entscheidet über das Skipt einen neuen User anzulegen pflegt das Skript den Zweiten User einfach auch in die config ein. Dann funktioniert erstmal gar nichts mehr und man muss es manuell in der config anpassen ;-)

**Comment by SBorg2014** [comment]
Danke für den Hinweis, ist/wird mit der 2.7.0 gefixt (bei bereits eingetragenem User wird nun die OSEM-Registrierung Eingangs abgebrochen).
