### ISSUE TITLE
Fehlermeldung seit JS-Controller 3.3.x

### ISSUE THREAD

**Issue by metaxa1** [SBorg2014/WLAN-Wetterstation#22]
Wo muss ich im Script was ändern damit diese Meldung im LOG nicht mehr kommt?

`
<html>
<body>

simple-api.0 | 2021-08-09 12:13:36.088 | info | (18475) State value to set for "javascript.0.Wetterstation.Info.Hitzeindex" has to be type "string" but received type "number"
-- | -- | -- | --

</body>
</html>`

**Comment by SBorg2014** [comment]
Bei den Objekten, hier dann "javascript.0.Wetterstation.Info.Hitzeindex". Unter "Common" stellst du einfach den "Zustandstyp" auf __gemischt (oder mixed)__ um. In der aktuellen 2.7.0 wird der Datenpunkt bereits als "mixed" angelegt, nutzt aber nix wenn man den Datenpunkt mit einer Vorgängerversion schon hatte... ;)

**Comment by metaxa1** [comment]
Habe ich schon mehrfach gemacht, wird von "Geisterhand" aber wieder auf Zahl zurückgestellt. M<chs aber gerne nochmal, hier das Ergebnis vor der "Geisterhand"
![grafik](https://user-images.githubusercontent.com/45742489/128761113-64e1a60c-a3b3-4382-82d1-726c9d6a5248.png)
Ich editiere diesen Beitrag wieder, sobald der Ghost wieder zuschlägt :-)

**Comment by SBorg2014** [comment]
Kann "eigentlich" nicht sein ^^
Zumindest das Skript ändert/legt welche an/löscht keine Datenpunkte.
Ev. blöde Frage, aber kann es sein, dass du noch das wetterstation.js (oder wie du es genannt hast) noch laufen hast? Dann würde es mit dem Start des ioBs bzw. JS-Controllers immer einmalig ausgeführt werden. Wenn du jetzt noch eine Version <2.7.0 des JavaScriptes hast wo noch "type: number" ist, würde er dir die Einstellung des Datenpunktes tatsächlich wieder überschreiben, ganz ohne "Ghost" 😁

**Comment by metaxa1** [comment]
Wie zu Fleiß :-)
Das Script läuft seit gestern einwandfrei und ohne Fehlermeldungen.
<html><body>


daswetter.0 | 2021-08-11 09:43:23.633 | info | (20782) cleaned everything up...
-- | -- | -- | --
daswetter.0 | 2021-08-11 09:43:23.094 | info | (20782) Terminated (NO_ERROR): Without reason
daswetter.0 | 2021-08-11 09:43:04.550 | info | (20782) starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.daswetter, node: v12.22.2, js-controller: 3.3.15


</body>
</html>

Lieben Dank für deine viele Arbeit!
