### ISSUE TITLE
jq: error (at <stdin>:7): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by bandimuc** [SBorg2014/WLAN-Wetterstation#23]
Hallo, mein Server meldet plötzlich folgenden Fehler "jq: error (at <stdin>:7): Cannot iterate over null (null)" und es kommt keine Kommunikation zu Stande. Was kann das sein ?
Ich habe bereits auf 2.10 umgestellt
Bin etwas ratlos
Danke im Voraus

**Comment by SBorg2014** [comment]
Hi, tritt das dauernd auf oder nur von 0:00 Uhr bis ~ 01:00 Uhr im 15 Minutenraster? Dafür habe ich gerade einen Fix im Test, allerdings ist "jq" nur ein "Schönheitsfehler". Der besagt hier lediglich, dass er etwas (genauer Sonneneinstrahlung) nicht verarbeiten kann. Das hat aber eigentlich nichts mit der Kommunikation zu tun, die sollte dennoch funktionieren.
Wenn du den Service stoppst (`systemctl stop wetterstation`) was liefert dann ein `./wetterstation.sh --debug` ?
Falls hier auch nix kommt, kannst du die IP des Displays/Gateways anpingen?

**Comment by bandimuc** [comment]
Hi, der jq Fehler ist immer noch da, aber die Verbindung steht nun über die Nacht,  Ping und Debug liefern die richtigen Werte. Nun habe ich nur noch das Problem, dass der Zeitstempel nicht alle 30 Sek neu gesetzt wird. Das heißt, die Daten in javascript.0.Wetterstation werden nicht regelmäßig aktualisiert.

**Comment by SBorg2014** [comment]
Das Skript kann nur etwas senden wenn es auch etwas empfängt. Wenn es also nicht regelmäßig was sendet, bekommt es schlichtweg nicht regelmäßig Daten (oder der Rechner wäre gerade schon total überlastet, allerdings ist das Skript in 1-2 Sekunden durch, braucht 5-10MB RAM + so gut wie keine Rechenleistung). Du kannst in der "conf" mal das Logging für paar Stunden aktivieren (service restarten nicht vergessen) und dann schauen wie regelmäßig die Daten kommen.
Sind da große Lücken, dann packe mal das Display/Gateway testweise etwas näher an den Router/AP.

**Comment by SBorg2014** [comment]
closed due to inactivity
