### ISSUE TITLE
ACK wird nicht auf true gesetzt

### ISSUE THREAD

**Issue by dan1-de** [SBorg2014/WLAN-Wetterstation#24]
Hi @SBorg2014,

vielen Dank für das Script. Es funktioniert einwandfrei.
Allerdings wird leider beim Update der Werte das ACK-Flag nicht auf true gesetzt. Dadurch funktioniert zum Beispiel der Statistics Adapter nicht.

Ich habe das jetzt momentan für die benötigten Werte über ein Javascript Script gelöst, das nach jedem Update das ACK auf true setzt. Es wäre schön, wenn es direkt mit deinem Script funktionieren würde.

Danke und viele Grüße
Daniel

**Comment by SBorg2014** [comment]
Hallo Daniel, das geht leider nicht so einfach. Einige Werte schreibe ich einzeln, da geht es. Alle einzeln zu schreiben dauert einfach zu lange, deswegen werden die meisten in einem Rutsch (per "setBulk") geschrieben. Da wird aber kein ACK-Flag unterstützt. Bei genügend Votes wird es ev. auch mal umgesetzt, also lass vielleicht auch mal einen dort. Issue von mir auf GitHub: https://github.com/ioBroker/ioBroker.simple-api/issues/29

**Comment by dan1-de** [comment]
Hallo @SBorg2014,

danke für die Rückmeldung. 
Ich habe jetzt auch mal einen Up-vote gegeben. Denke aber nicht das sich da so schnell etwas tut. Ist ja immerhin schon 2 Jahre alt.

Wir könnten ggf. einmal anfragen, ob wir das im simple API Adapter umsetzen dürfen...

Viele Grüße

**Comment by SBorg2014** [comment]
Och fragen muss man da nicht, ein Pull Request genügt 😃
Ich kann zwar einigermaßen JS, aber Core...?
Ich sehe
`adapter.setForeignState(id, values[usedId], false, {`
als das Problem an, denn hier wird anscheinend per Default immer "false" gesetzt, obwohl der ACK-Status im Array angelegt wird. Werde es mal "brutal" versuchen hier auf "true" umzustellen.
