### ISSUE TITLE
Many log entries in daemon.log

### ISSUE THREAD

**Issue by stefanerdmann** [SBorg2014/WLAN-Wetterstation#25]
Hi,

there are a lot of log entries in the daemon.log:

Dec 11 17:09:32 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 7224 received!
Dec 11 17:09:35 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:09:59 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 36302 received!
Dec 11 17:10:02 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:10:31 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 34567 received!
Dec 11 17:10:34 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:11:03 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 15790 received!
Dec 11 17:11:06 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:11:32 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 36617 received!
Dec 11 17:11:35 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:11:51 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 44360 received!
Dec 11 17:11:54 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:12:23 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 39445 received!
Dec 11 17:12:26 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:12:39 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 13641 received!
Dec 11 17:12:42 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:13:11 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 35319 received!
Dec 11 17:13:14 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)
Dec 11 17:13:32 raspberrypi wetterstation.sh[483]: Connection from 192.168.178.68 46116 received!
Dec 11 17:13:35 raspberrypi wetterstation.sh[483]: Listening on [0.0.0.0] (family 2, port 1080)

Is it possible to deactivate it? I dont think that this kind of information is useful in this kind of log file

**Comment by SBorg2014** [comment]
Hi,
this is fixed since V2.10.0 :
`+ netcat-/Success-Meldungen im Syslog entfernt`

So you should update to Version V2.10.1 (only two entries from starting the service left)

Regards
SBorg
