### ISSUE TITLE
Communication failure not reset

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#26]
Hallo.
Hatte heute Nacht eine Kommunikationsstörung auf meinem WLAN, das das Script auch korekt mit setzten von Objekt
'_Kommunikationsfehler' auf 'true' berichtete.
Leider steht dieser DP immer noch auf 'true', auch obwohl die Kommunikation wieder funktioniert und alle DP richtig gelesen bzw. zum ioBroker geschrieben werden.

Kurze Codeanalyse hat gezeigt, dass der 'DP_KOMFEHLER' nur beim Script-Start in Prozedur 'setup()' auf 'false' resetiert wird, nicht aber im laufenden Betrieb wenn der Ausfallszähler '$KOMFEHLER' wieder '0' erreicht hat. 

Weiters: der Ausfallszähler zählt ja bei nicht empfangenen Daten bis in's Unendliche, bei korrektem Datenempfang wird dann dieser Zähler wieder bei jedem korrektem Datenempfang bis auf '0' zurückgezählt. Also: je länger der Ausfall, umso länger muss er auch wieder bis '0' zurückzählen...

fast vergessen: Script-Version 2.11.0

lg
Manfred

**Comment by SBorg2014** [comment]
Hi,
dass ist extra so implementiert. Gelegentliche Fehler werden so wieder gegen 0 gezählt, "echte" Störungen (>=10 Fehler in Folge) bleiben aber erhalten, da hier normalerweise wirklich ein Problem vorliegt.
Grundgedanke ist der, dass man sich den DP in der VIS anzeigen lässt, die Fehlerquelle kontrolliert/behebt und es dann per VIS quittiert (= den DP wieder auf *false* setzt).

Es wäre aber ev. eine Überlegung wert ob man das Verhalten in der "conf" einstellen kann. Da bin ich aber etwas zwiegespalten, Zum einen soll sich jeder alles so einstellen können wie er/sie/es mag, zum anderen verwirren aber vielfältige Einstellungsmöglichkeiten auch mehr.

Gruß
SBorg

**Comment by mango1402** [comment]
Hallo SBorg,
OK, versteh nun die Philosophie dahinter. Störung muss eben 'quttiert' werden. Geht dies auch aus Grafana statt VIS?

Wenn man aber (zumidest die bei mir verwendeten) anderen Komponenten im ioBroker betrachtet, werden hier Kommunikationsstörungen automatisch zurückgesetzt. Macht ja meistens auch Sinn, wenn das Problem weder am 'Sender' noch am 'Empfänger' liegt, sondern an der Übertragungsstrecke (z.B. Routerausfall). Wenn diese Störung behoben ist, braucht es eigentlich auch keine Kommunikationsstörung mehr anzeigen.
Alternativ könnte man auch einen dritten Status einführen, der eine 'vergangene, noch nicht quittierte Störung' anzeigt.

Ideen gäbe es viele - Entscheidung liegt bei Dir ;)

Möchte trotzdem aber auch Danke für die Bereitstellung dieser Funktion(en) sagen! Tolle Arbeit, mach weiter so!

lg
Manfred

**Comment by SBorg2014** [comment]
Hallo Manfred,
ist halt wie üblich: frag zwei Leute, dann hast du drei Meinungen ;)

> Geht dies auch aus Grafana statt VIS?
   
Na Logo, du kannst den mit was auch immer resetten. Du legst im passenden Panel bei den "Panel Options" einen "Panel Link" an. Ich kann hier leider nur schlecht Bilder anhängen, deswegen wäre es uU. im ioB-Forum dann besser zu erklären falls es hakt.
Der Link ruft dann die SimpleAPI an (IP, Port und DatenPunkt natürlich anpassen ^^): `http://192.168.1.3:8087/set/javascript.0.Wetterstation._Kommunikationsfehler?value=false&ack=true` 

Ich komme halt aus der Elektronikecke. Wenn es im Fehlerfall die Sicherung schmeißt, bleibt die halt auch "Aus"... ;)
Ich habe mir aber schon Gedanken gemacht und werde es konfigurierbar machen. Dann kann jeder wie er will und per Default bleibt es so wie es aktuell ist. Dann hat auch keiner ein Problem wenn er auf eine neue Version updated.

Grüße
SBorg

**Comment by mango1402** [comment]
Danke für den Grafana-Crashkurs ;) Wirklich cool was man mit dem Ding alles machen kann.
Ich wer'd mir auch ein Reset-Script bauen, dann bekomm ich auch gleich einen Fehlereintrag im ioBroker-Log.

lg
Manfred

**Comment by SBorg2014** [comment]
Upload folgt voraussichtlich heute, lässt sich dann ab der V.2.11.0 konfigurieren.

btw: [Beschreibung Kom-Fehler](https://github.com/SBorg2014/WLAN-Wetterstation/wiki/FAQ---Troubleshooting/#was-ist-der-datenpunkt-_kommunikationsfehler-)

**Comment by mango1402** [comment]
Danke für die Beschreibung im Wiki - oder hab ich das vorher schon überlesen?

Machst Du vom 2.11.0 jetzt ein re-release?

**Comment by SBorg2014** [comment]
Das stand schon vorher da, habe es nur um den Part des neuen Parameters erweitert.

> Machst Du vom 2.11.0 jetzt ein re-release?

Nein, denn die Änderungen sind im "master"-Branch, was quasi noch als Beta-Status zählt. Released ist bisher nur bis V2.10.1
Wenn dann paar Tage alles ohne Fehler lief. kommt dann das Release, zumindest wenn genügend Neuerungen vorhanden sind.

**Comment by mango1402** [comment]
Danke!
hab installiert, läuft einwandfrei.
Fehler resettiert sich nach 10 erfologreich empfangenen Telegrammen wieder selbst.

**Comment by SBorg2014** [comment]
Danke für die Rückmeldung, dann werde ich es die Tage releasen, da aktuell sonst nix auf der fertigen Agenda steht ;)
