### ISSUE TITLE
JavaScript error after Statistik-script update

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#27]
Hallo,
nach einem Update von 2.6.0 auf 2.10.0 bekomme ich regelmäßig beim Durchlaufen vom Statistik-Script folgende Fehlermeldung:

> 2021-12-16 01:03:00.069 - debug: javascript.0 (23274) sendTo "query" to system.adapter.influxdb.0 from system.adapter.javascript.0: select * FROM "0_userdata.0.Wetterstation.Aussentemperatur" WHERE time >= 1639522800000000000 AND time <= 1639609199000000000; select * FROM "0_userdata.0.Wetterstation.Wind_max" WHERE time >= 1639522800000000000 AND time <= 1639609199000000000; select * FROM "0_userdata.0.Wetterstation.Regen_Tag" WHERE time >= 1639522872000000000 AND time <= 1639609199000000000
>
> 2021-12-16 01:03:00.073 - info: javascript.0 (23274) script.js.common.Wetterstatistik_1_0_0: Auswertung durchgeführt...
> 
>**2021-12-16 01:03:00.910 - error: javascript.0 (23274) script.js.common.Wetterstatistik_1_0_0: error: TypeError: Cannot read property '0' of null**

(debug vom Javascript-Adapter ist aufgedreht)

hast Du eine Idee woran dies liegen kann?

Danke,
lg
Manfred

**Comment by SBorg2014** [comment]
Das hat nichts mit dem Update bzw. dem Shell-Skript direkt zu tun.
Das ist ein bekannter Fehler vom Statistik-Skript. Leider ist da JS "sehr" aussagekräftig wo der Fehler auftritt (IRONIE aus). Ich habe schon paar Änderungen vorgenommen, leider bisher ohne Erfolg. Er möchte da einen Wert lesen den es zu dem Zeitpunkt noch nicht gibt.
Ev. finde ich den Fehler auch mal, aber das passiert nur einmalig pro Tag und ist "reine Optik". Soll so zwar nicht sein, aber hat sonst keinerlei Auswirkung.

**Comment by mango1402** [comment]
ist auch im Javascript-Debug mode reproduzierbar.
dort schreibt er nichts, damit kann man das Script öfters laufen lassen.

Kann ich Dir irgendwelche Debug-Meldungen einbauen und beisteuern?

**Comment by SBorg2014** [comment]
Nicht mehr nötig, Fehler gefunden. Wenn es den finalen Test heute Nacht besteht gibt es voraussichtlich dann am Sonntag ein Update :-)

Allerdings war es doch etwas mehr als ein Schönheitsfehler, die ganze Funktion des Script-Updatechecks lief nicht korrekt. Da aber seit 3 Monaten kein Update mehr von mir kam, ist es so auch nicht weiter aufgefallen, außer der einen Fehlerzeile...

**Comment by SBorg2014** [comment]
Fixed [939f817fcefd6160c89d4ec9d0dfc7bca0d21a98](https://github.com/SBorg2014/WLAN-Wetterstation/commit/939f817fcefd6160c89d4ec9d0dfc7bca0d21a98#diff-134909f498416be9cc80142b85cf04c80667c46e762f76548aaf5c627f19a150)
