### ISSUE TITLE
Zeile 687: [: : Ganzzahliger Ausdruck erwartet - Portadresse des socket.io scheint nicht "verträglich"

### ISSUE THREAD

**Issue by IO-Link** [SBorg2014/WLAN-Wetterstation#28]
Guten Abend,

ich bin durch die Installation so weit sehr gut durchgekommen und es hat alles geklappt - insbesondere  Dank der hervorragenden Beschreibung. Der Test ist allerdings erfolglos.

Der Port meiner socket.io Instanz in ioBroker ist **8084** - warum-auch-immer NICHT der Standard 8087
Trage ich "8087" erscheint erwartungsgemäß "...connection refused"
Bei "8084" erscheint:

_Connection to 192.168.178.121 8084 port [tcp/*] succeeded!
parse error: Invalid numeric literal at line 1, column 4
(standard_in) 1: syntax error
(standard_in) 1: syntax error
/home/iobroker/wetterstation.sub: Zeile 687: [: : Ganzzahliger Ausdruck erwartet.
parse error: Invalid numeric literal at line 1, column 4
(standard_in) 1: syntax error
(standard_in) 2: syntax error
/home/iobroker/wetterstation.sub: Zeile 339: /86400: Syntax Fehler: Operator erwartet. (Fehlerverursachendes Zeichen ist \"/86400\")._

Wie bei Issue #6  habe ich es schon mit netcat-openbsd versucht - leider ohne Erfolg.

Hast du evtl. noch eine Idee?

**Comment by IO-Link** [comment]
bin ein wenig weitergekommen. Ich habe nun in der .conf in der Zeile
WS_PROTOKOLL=9 gewählt. Vorher hatte ich fälschlicherweise "1" drinstehen. 
Nun bekomme ich im in der console Daten angezeigt:

` WLAN-Wetterstation V2.11.0 - (c)2019-2021 by SBorg
 Config-Version: V2.11.0
 Sub-Version   : V2.11.0

 'bc' installiert: [✓]
 'jq' installiert: [✓]

 'nc' in der Openbsd-Variante installiert:  [✓]
 'netcat' in Openbsd-Variante aktiv, alles korrekt [✓]


Connection to 192.168.178.121 8084 port [tcp/*] succeeded!
parse error: Invalid numeric literal at line 1, column 4
(standard_in) 1: syntax error
(standard_in) 1: syntax error
/home/iobroker/wetterstation.sub: Zeile 687: [: : Ganzzahliger Ausdruck erwartet.
Not Implemented

Messwerteblock: 21.27 19.38 9.61 19.38 49 53 0 0 8 951.03 1011.41 0 0 .7 1.0 0 0.00 0 04.01.2022%2021:05:43 EasyWeatherV1.6.1


Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

Temperatur Innen        : 21.27 °C
Temperatur Aussen       : 19.38 °C
Taupunkt                : 9.61 °C
Gefühlte Temperatur     : 19.38 °C
Luftfeuchte Innen       : 49 %
Luftfeuchte Aussen      : 53 %
Windgeschwindkeit       : 0 km/h
Windböengeschwindkeit   : 0 km/h
max. Windböe            :  km/h
Windrichtung            : 8 °
Windrichtung            : N
Luftdruck absolut       : 951.03 hPa
Luftdruck relativ       : 1011.41 hPa
Regenrate               : 0 mm/h
Regenstatus             :
Regen seit Regenbeginn  :  mm
Regen Stunde            :  mm
Regen Tag               : 0 mm
Regen Woche             : .7 mm
Regen Monat             : 1.0 mm
Regen Jahr              : 0 mm
Regen Gesamt            :  mm
Sonnenstrahlung         : 0.00 W/m²
UV-Index                : 0
Zeitstempel             : 04.01.2022 21:05:43
Firmware                : EasyWeatherV1.6.1
Batteriestand:          :
Gateway-Modell          :

Zusatzsensoren:



Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=21.27&javascript.0.Wetterstation.Aussentemperatur=19.38&javascript.0.Wetterstation.Taupunkt=9.61&javascript.0.Wetterstation.Gefuehlte_Temperatur=19.38&javascript.0.Wetterstation.Innenfeuchtigkeit=49&javascript.0.Wetterstation.Aussenfeuchtigkeit=53&javascript.0.Wetterstation.Wind=0&javascript.0.Wetterstation.Wind_max=0&javascript.0.Wetterstation.Windrichtung=8&javascript.0.Wetterstation.Druck_absolut=951.03&javascript.0.Wetterstation.Druck_relativ=1011.41&javascript.0.Wetterstation.Regenrate=0&javascript.0.Wetterstation.Regen_Tag=0&javascript.0.Wetterstation.Regen_Woche=.7&javascript.0.Wetterstation.Regen_Monat=1.0&javascript.0.Wetterstation.Regen_Jahr=0&javascript.0.Wetterstation.Sonnenstrahlung=0.00&javascript.0.Wetterstation.UV_Index=0&javascript.0.Wetterstation.Zeitstempel=04.01.2022%2021:05:43&javascript.0.Wetterstation.Info.FW_Version=EasyWeatherV1.6.1&javascript.0.Wetterstation.Regenstatus=&javascript.0.Wetterstation.UV_Belastung=keine&javascript.0.Wetterstation.Windrichtung_Text=N&javascript.0.Wetterstation.Info.Hitzeindex=


DATA von Wetterstation:
GET /weatherstation/updateweatherstation.php?ID=xxxxxx&PASSWORD=xxxxxx&indoortempf=70.3&tempf=66.9&dewptf=49.3&windchillf=66.9&indoorhumidity=49&humidity=53&windspeedmph=0.0&windgustmph=0.0&winddir=8&absbaromin=28.084&baromin=29.867&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.031&monthlyrainin=0.043&yearlyrainin=0&solarradiation=0.00&UV=0&dateutc=2022-01-04%2020:05:43&softwaretype=EasyWeatherV1.6.1&action=updateraw&realtime=1&rtfreq=5 HTTP/1.1


Debug VAR:
Installationsverzeichnis: /home/iobroker
IPP: 192.168.178.121:8084       WS_PORT: 1080           WS_POLL: 60             PRE_DP: javascript.0.Wetterstation
WEB: HTTP               WS_PROT: Sainlogic Pro  DP40/50/60/70/100/200/250/300: 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
WH31: 0
Script-Version: V2.11.0 Config-Version: V2.11.0 Sub-Version: V2.11.0
`

Allerdings kommt leider im iobroker Datenpunkt nichts an.  Steht alles auf "0"...

**Comment by SBorg2014** [comment]
Hi,
der benutzte Port ist nicht maßgeblich, er muss nur frei sein. 8084 wäre also so Ok.
Die Fehlermeldungen und das Hauptproblem gehören zusammen. Bei den Fehlermeldungen kann er vom ioB nichts lesen. Es klemmt also an der Verbindung vom/zum ioBroker (deswegen kommen auch keine Daten an).
Versuche ev. mal einen ganz anderen Port und/oder setze mal von dem Rechner aus auf dem das Skript laufen soll ein `curl  http://192.168.178.121:8084/set/javascript.0.Wetterstation.Innentemperatur?value=999&ack=true` ab ob er da was schreibt (Dann sollten 999°C bei der Innentemperatur im ioB stehen).

**Comment by IO-Link** [comment]
> Hi, der benutzte Port ist nicht maßgeblich, er muss nur frei sein. 8084 wäre also so Ok. Die Fehlermeldungen und das Hauptproblem gehören zusammen. Bei den Fehlermeldungen kann er vom ioB nichts lesen. Es klemmt also an der Verbindung vom/zum ioBroker (deswegen kommen auch keine Daten an). Versuche ev. mal einen ganz anderen Port und/oder setze mal von dem Rechner aus auf dem das Skript laufen soll ein `curl http://192.168.178.121:8084/set/javascript.0.Wetterstation.Innentemperatur?value=999&ack=true` ab ob er da was schreibt (Dann sollten 999°C bei der Innentemperatur im ioB stehen).

Danke für die schnelle Rückmeldung.

Leider hat die Änderung des Ports und  `curl` nichts gebracht. Bei Ausführung von `./wetterstation.sh --debug` bleibt die Fehlermeldung identisch, egal welcher Port.

`curl http://192.168.178.121:8084/set/javascript.0.Wetterstation.Innentemperatur?value=999&ack=true` bringt:

**[1] 6391
jonny@ioBroker-V2:/home/iobroker$ Not Implemented
[1]+  Fertig                  curl http://192.168.178.121:8084/set/javascript.0.Wetterstation.Innentemperatur?value=999**

Leider bleibt der Datenpunkt javascript.0.Wetterstation.Innentemperatur leer bzw. 0°C.

iobroker und alle Adapter sind auf dem neuesten Stand. Die Einstellung in der socket-io instanz sind:
![2022-01-05 10_53_27-Window](https://user-images.githubusercontent.com/45272881/148197923-05ac85c2-e844-4b6e-acaa-27f3f2259374.png)

**Comment by FB500** [comment]
Laut der Installationsanleitung braucht man wohl den IOBroker Adapter "Simple RESTful API" (der defaultmäßig Port 8087 nutzt).
Soweit ich Dich, @IO-Link , verstehe, versuchst du aber den Adapter "socket.io" zu nutzen (default Port 8084).
Ist letzteres unterstützt, @SBorg2014 ?

**Comment by IO-Link** [comment]
> Laut der Installationsanleitung braucht man wohl den IOBroker Adapter "Simple RESTful API" (der defaultmäßig Port 8087 nutzt). Soweit ich Dich, @IO-Link , verstehe, versuchst du aber den Adapter "socket.io" zu nutzen (default Port 8084). Ist letzteres unterstützt, @SBorg2014 ?

Oh... Das ist jetzt sehr, sehr peinlich.. 

Tatsächlich war keine Instanz des Adapters "Einfache RESTful API" installiert. Ich dachte die Instanz "socket.io" gehört zu dem Simple RESTful API Adapter - stimmt aber nicht.
Nachdem ist eine "richtige" Instanz des Simple RESTful API Adapters installiert habe, funktioniert es ohne Probleme! Vielen Dank für den Hinweis!
