### ISSUE TITLE
ws_updater.sh problem in Version 2.11.1

### ISSUE THREAD

**Issue by schlaubstar** [SBorg2014/WLAN-Wetterstation#29]
Hallo und vielen lieben Dank für diese tolle Implementierung um die Wetterstationen an den IoB zu koppeln.
Allerdings habe ich seit dem Update auf V2.11.1 folgendes Problem,
wenn ich die ws_update.sh ausführe, erhalte ich folgende Ausgabe:

```console
 ┌────────────────────────┐
 │                        │
 WS-Upda  │ V2.11.1
 │                        │
 └────────────────────────┘

ws_updater.sh: Zeile 17: $'\r': Kommando nicht gefunden.
ws_updater.sh: Zeile 18: $'\r': Kommando nicht gefunden.
ws_updater.sh: Zeile 19: $'\r': Kommando nicht gefunden.
ws_updater.sh: Zeile 20: Syntaxfehler beim unerwarteten Wort `$'{\r''
's_updater.sh: Zeile 20: `checker() {
foo
```
Der Fehler scheint von dem Code: ${BL} das als  BL='\e[1;36m' definiert ist zu stammen, entferne ich ihn, läuft das Script wieder.
Vielleicht kannst Du das bei Gelegenheit mal anschauen.
Vielen lieben Dank !

**Comment by SBorg2014** [comment]
Hi, danke und danke für den Hinweis. Das Zip-File war wohl korrupt oder ich habe einen Fehler beim packen begangen (dann sollte aber eigentlich auch was am Skript kaputt gehen). Zumindest habe ich es nochmals gepackt, hochgeladen und anschließend ausprobiert. Sollte jetzt funktionieren :)

**Comment by schlaubstar** [comment]
Super ! Vielen Dank ! Jetzt geht wieder alles !
