### ISSUE TITLE
Statistik am Monatsersten nicht vollständig

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#32]
Hallo,
Auf der Suche nach dem fehlenden Vortages-Regenwert bin ich darauf gestoßen, dass jeweils am Monatsersten das Script mit 'return' abgebrochen wird, ohne die restlichen Statistiken zu rechnen. Es kommt auch im Log keine Entsprechende Meldung dass 'Auswertung durchgeführt' wäre.
Ist dies so gewollt? Ich denke nicht.....

lg
Manfred

**Comment by schlaubstar** [comment]
Hi Manfred, 
nachdem Du Dir offensichtlich die Mühe gemacht hast, dem Problem auf den Grund zu gehen: Willst Du vielleicht noch ein paar Details teilen wie in welcher Funktion/Zeile des Scripts das Problem auftritt ?

**Comment by SBorg2014** [comment]
> Ist dies so gewollt? Ich denke nicht.....

Doch, genau darüber steht auch "//nun beenden" 😉
Der Grund ist auch recht simpel, es gibt am Monats ersten nix weiter zu tun. Wenn das Skript heute Nacht um 01:03 Uhr (default) lief, hast du für den April da nur eine Handvoll Messwerte von 0:00 Uhr bis 1:03 Uhr. IMO recht mager, um da von Monatswerten (nicht mal Tageswerte, es fehlen dann ja immer noch 23 Stunden für den aktuellen Tag) zu sprechen. Deswegen wird das dann ab dem 02. des Monats erst ausgeführt, dann kann man auch sagen war ein warmer/kalter/sonst was Tag im April, Höchst-/Tiefstwert usw. Würde das Skript am 01. schon kpl. durchlaufen, würdest du anhand der Daten von 0:00 - 1:03 Uhr schon bestimmen zB. "was" für ein Tag das war...
Ein aktuelles Problem ist aber, dass mit einer Änderung vom November die Monatswerte nicht mehr zurückgesetzt werden. Das hat aber eine andere Ursache die ich hoffentlich beseitigt habe. Da ich allerdings nur mein Produktivsystem zum testen habe, heißt es da leider bis zum 01.05. abwarten :( (ein temporärer Q&D-Fix steht im Forum)

**Comment by mango1402** [comment]
OK danke.
Aber:
es fehlen dann jeden Ersten im Monat die Werte vom Vortag:

```
    //VorTag
    setState(PRE_DP+'.VorTag.Temperatur_Tiefstwert', Tiefstwert, true);
    setState(PRE_DP+'.VorTag.Temperatur_Hoechstwert', Hoechstwert, true);
    setState(PRE_DP+'.VorTag.Temperatur_Durchschnitt', Temp_Durchschnitt, true);
    setState(PRE_DP+'.VorTag.Regenmenge', Max_Regenmenge, true);
    setState(PRE_DP+'.VorTag.Windboe_max', Max_Windboe, true);

```
denn diese sind ja nicht die von 00:00 bis 01:03, sondern eben die vom Tag zuvor und da sollten ja 24h vorhanden sein....

lg
Manfred

**Comment by SBorg2014** [comment]
Da hast du "leider" Recht (man merkt wohl: ich nutze es selbst gar nicht) und ist bis dato keinem aufgefallen...
...aber schon eine Idee, man muss nur den Ausstieg und die Reihenfolge der Abläufe neu definieren. Denn ohne Influx-Abfrage gibt es auch keine VorTages-Werte.

**Comment by SBorg2014** [comment]
Sollte mit der V1.1.0 nun gefixt sein. Wird der 01. Mai zeigen... ;)

**Comment by mango1402** [comment]
Script V1.1.0 installiert, bis dato OK.
Jetzt mal warten auf den 1. Mai......
