### ISSUE TITLE
Statistik 'Regen Vortag'

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#35]
Hallo,

Bin mir nicht sicher ob dies wirklich ein Bug ist oder ich was falsch mache.

Mein Problem: 
Statistik-Sctipt Version 1.1.1
im Datenpunkt 'VorTag.Regenmenge' steht 'null', falls es am Vortag nicht geregnet hat.
Influx ignoriert dies und speichert somit leider nichts ab (also auch nicht '0,0').
Damit ist die Statistik vom Vortag nicht korrekt auszuwerten.

Ich denke, hier müsste das Statistiksript prüfen, ob die Berechnung gültig ist:
`Max_Regenmenge = Math.max(...regen);`
da kommt nämlich '.Infinite' raus, falls keine Datensätze für Regeneinträge vorhanden sind.
```
2022-06-15 01:03:00.031 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Auswertung durchgeführt...
2022-06-15 01:03:00.423 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Daten ab 14. Jun 2022 00:00:00
2022-06-15 01:03:00.424 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Daten bis 14. Jun 2022 23:59:59
2022-06-15 01:03:00.424 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Erster Messwert: 2022-06-13T22:01:03.506Z ***13.5
2022-06-15 01:03:00.424 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Letzter Messwert: 2022-06-14T21:59:58.802Z ***13.61
2022-06-15 01:03:00.425 - info: javascript.0 (2066) script.js.common.Wetterstatistik.Wetterstatistik_script: Anzahl Datensätze: T_1287\|W_1403\|R_0

```
und
`setState(PRE_DP+'.VorTag.Regenmenge', Max_Regenmenge, true);`
schreibt dann eben scheinbar 'null' auf den Datenpunkt.
Und Influx mach dann eben nix:

> Additionally, InfluxDB do not support "null" values, so these are not written at all into the DB.

Quelle: https://github.com/ioBroker/ioBroker.influxdb

kann auch sein, das ich was falsch eingestellt habe, aber auch der Switch 'Zero- oder Nullwerte ignorieren (==0)' ändert gar nichts am Verhalten.

Danke,
lg
Manfred

**Comment by SBorg2014** [comment]
Hi Manfred,
ich sag mal Jein ;)
Eigentlich sollte man bei Influx zumindest einen Wert mal täglich "erzwingen" (ist nachher besser für Grafanagraphen). Bei Influx "trotzdem gleiche Werte aufzeichnen" zB. 43200 Sekunden = alle 12 Stunden mal was in den Datensatz reinschreiben.
Dann kommt auch kein Fehler mehr, trotzdem **muss** man das ja nicht zwingend so machen, dann hast du aber den "Null"-Fehler. Habe ich schlichtweg nicht auf dem Schirm gehabt und wohl noch keinem aufgefallen 🙃
Probier einfach mal (sollte funktionieren) so ~ bei Zeile 191 den Regenmax-Part zu ändern:

```
//Regen    
   if (regen.length=0) {Max_Regenmenge=0;} else {Max_Regenmenge = Math.max(...regen);}
```

**Comment by mango1402** [comment]
Danke für die rasche Antwort.
gestern noch eingebaut - funktioniert leider nicht.
Muss bei Javascript bei If-Abfragen auch das doppel '==' verwendet werden?
Oder wäre ein '<1' günstiger?

Nächster Test wahrscheinlich erst am Samstag - für heute wurde Regen angesagt....

lg
Manfred

**Comment by SBorg2014** [comment]
Würde sagen Test bestanden ^^
Aber Spaß beiseite, du hast völlig Recht. Ein Gleichheitszeichen ist bei JS eine Zuweisung, zwei dann der notwendige Vergleich (und um den geht es ja). Vergesse ich gelegentlich immer mal wieder und gerade blöd, weil ich es nicht getestet habe (oder kann, da ich ja immer mindestens einen 0-Wert bei mir in der Influx stehen habe).  
Da laut deinem Debug von oben "R_0" (=Länge bzw. Anzahl Datensätze des Arrays der Regenwerte; hier jetzt "0") macht es keinen Unterschied ob "==0" oder "<1", da die Länge eines Arrays nur 0...n betragen kann, aber nie negativ wird (was dann für "<1" sprechen würde).

```
//Regen
    if (regen.length == 0) { Max_Regenmenge = 0; } else { Max_Regenmenge = Math.max(...regen); }
```
Die zusätzlichen Leerzeichen müssen nicht, habe ich mir nur aus "Lesbarkeitsgründen" so angewöhnt.

**Comment by mango1402** [comment]
Hallo!
So, jetzt funktioniert's richtig. Steht sauber '0' im DP und auch Influx hat korrekt aufgezeichnet.
Ist zwar eher unwahrscheinlich, aber für die 'Max_Windboe' würd der Einbau auch Sinn machen.
Danke!
lg
Manfred

**Comment by SBorg2014** [comment]
Unwahrscheinlich, aber dennoch möglich --> ist drin (Fixed in V1.1.2 https://github.com/SBorg2014/WLAN-Wetterstation/commit/5aaf83327fc19eac4a0fb75dff6b800b6cd1fa1e)
