### ISSUE TITLE
Update auf V2.16.0 schlägt fehl

### ISSUE THREAD

**Issue by schlaubstar** [SBorg2014/WLAN-Wetterstation#37]
Hi, beim Versuch mittels ws_updater.sh von V2.15.0 auf V2.16.0 zu kommen passiert bei mir folgendes:

`

         Auswahlmenü für WLAN-Wetterstation:
        _____________________________________

         [1] im aktuellen Verzeichnis installieren

         [2] als Service einrichten

         [3] Konfigurationsdatei patchen

         [4] Update ausführen

         [E] Exit

         Ihre Auswahl: [1-4]: 4

 ┌────────────────────────┐
 │                        │
 │   WS-Updater V2.16.0   │
 │                        │
 └────────────────────────┘

 'bc' installiert: [✓]
 'jq' installiert: [✓]
 'dc' installiert: [✓]
 'unzip' installiert: [✓]
 'patch' installiert: [✓]

 Zugriff auf 'Rest-API' im ioBroker: [✗]
  (Dies ist kein Problem, es können nur keine neuen Datenpunkte bei Bedarf automatisch angelegt werden.
  Dies muss im Fall neuer Datenpunkte per 'wetterstation.js' von Hand im ioBroker erfolgen.)

 Aktuelle Version (latest) auf GitHub: V2.16.0 vom 12.07.2022
 Version im aktuellen Verzeichnis    : V2.15.0

 Informationen zum Release V2.16.0:
 ─────────────────────────────────────────────────────────────

 Neu/Änderungen im Release:

 + Windrichtung der letzten 10 Minuten für alle Stationen (benötigt wird dafür nun noch 'dc')
 + durchschnittliche Windgeschwindigkeit der letzten 10 Minuten für alle Stationen
 ~ Bugfix gelegentlicher "jq parse"-Fehler
 ~ Bugfix Regenmenge des meteorologischen Sommers aktualisiert sich nicht

 Soll ein Update von WLAN-Wetterstation durchgeführt werden? [J/N]: J

 Führe Update aus...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34484  100 34484    0     0  66700      0 --:--:-- --:--:-- --:--:-- 66700
Archive:  tmp.zip
V2.16.0
  inflating: wetterstation.js
  inflating: wetterstation.sh
  inflating: wetterstation.sub
  inflating: ws_updater.sh
./ws_updater.sh: Zeile 2: $'\r': Kommando nicht gefunden.
./ws_updater.sh: Zeile 4: $'\r': Kommando nicht gefunden.
./ws_updater.sh: Zeile 11: $'\r': Kommando nicht gefunden.

 ┌────────────────────────┐
 │                        │
 WS-Upda  │ V2.15.0
 │                        │
 └────────────────────────┘

./ws_updater.sh: Zeile 17: $'\r': Kommando nicht gefunden.
./ws_updater.sh: Zeile 37: Syntaxfehler beim unerwarteten Wort `$'{\r''
'/ws_updater.sh: Zeile 37: `checker() {

`

**Comment by schlaubstar** [comment]
Ich glaube die ws_updater.sh in Deinem Release-File hat ein falsches Zeilenende. Mit Dos2Unix konnte ich das Ding wieder reparieren und ausführen. Allerdings ist die ws_updater.sh bei V2.15.0 stehen geblieben ! ;-)

**Comment by SBorg2014** [comment]
Moin, ja und nein ;-)
Das trat systembedingt während der Beta-Tests bei keinem Tester auf und ist ein (Denk-)Ansatzfehler. Man startet den Updater lokal und der öffnet dann einen child-Prozess mit dem aktuellen Updater auf GitHub. Der beendet sich nun ggf. wenn er feststellt das eine Voraussetzung fehlt (wäre aktuell der 'dc' als Hilfe für Berechnungen) damit der Nutzer ihn nachinstallieren kann. Das hat aber die unangenehme Folge, dass der ursprünglich zuerst gestartete Prozess nun als Zombie im System hängt. Startet man nun den Updater nochmals kommt es zur (falschen) Meldung "..." weil er mit dem Zombie kollidiert. 
Ist mit [gefixed](https://github.com/SBorg2014/WLAN-Wetterstation/commit/2c20ddd862015170cfb78e86cd32e1e24b9d4945)
