### ISSUE TITLE
Trockenperiode ist immer 0 Tage

### ISSUE THREAD

**Issue by neunteufels** [SBorg2014/WLAN-Wetterstation#38]
Hallo,

alle Werte in Bezug auf Trockenperiode (egal ob Jahreswerte oder Rekordwerte) werden mit 0 Tage angezeigt.
Ich kann mit Sicherheit sagen, dass es nicht jeden Tag geregnet hat. ;-)
![image](https://user-images.githubusercontent.com/34138765/182019295-77d7ee22-460c-485b-8382-22a99f0b1602.png)

Bitte um Check bzw. Erklärung.

Danke!

lg

**Comment by SBorg2014** [comment]
Hi,
zumindest funktioniert es (noch) pauschal, denn bei mir aktualisiert es sich noch und im Forum hat auch noch niemand "gemeckert ;) ". Steht irgendwas im ioB-Log diesbzgl.? Regenmenge etc. funktioniert aber soweit (darauf basiert dann der Rest)? Hast du in der wetterstation.conf `LAST_RAIN=` auf "DIFF" stehen?

**Comment by neunteufels** [comment]
Hallo,
sorry, hab komplett vergessen, dass ich das ins Forum schreiben könnte.
Regenmenge etc. funktioniert und stimmt soweit.
LAST_RAIN=DATUM
Im log steht nichts diesbezüglich.

**Comment by SBorg2014** [comment]
Jupp, das geht aktuell nicht (habe ich aber auch offen gestanden vergessen zu implementieren). Muss ich mir die Tage mal zu Gemüte führen. Aktuell geht es nur mit `LAST_RAIN=DIFF`
Anscheinend nutzt das wohl auch jeder, sonst wäre das schon früher mal aufgefallen ;-)

**Comment by neunteufels** [comment]
Ich hab mal auf `DIFF` umgestellt.
Mal schauen ob da was kommt mit der Zeit.

**Comment by SBorg2014** [comment]
Bestimmt :)
Sollte nun aber auch mit "Datum/Unix" funktionieren (aktuell aber noch ungetestet, allerdings mehr wie nicht funktionieren kann es auch nicht). Ev. [fixed](https://github.com/SBorg2014/WLAN-Wetterstation/commit/2bcc1fdab1af850ba87a1d4425a6f741d71c1c8d)

**Comment by neunteufels** [comment]
DIFF hat funktioniert.
Die anderen beiden habe ich nicht mehr getestet.
For me closed.
