### ISSUE TITLE
Wetterstation.sh funktioniert nach Update auf v2.0.17 nicht mehr

### ISSUE THREAD

**Issue by schlaubstar** [SBorg2014/WLAN-Wetterstation#39]
Hi, 

nach einem eigentlich erfolgreichen Update auf v2.0.17 bekomme ich beim debug-Aufruf nur folgende Meldung in einem endlos loop:

(standard_in) 1: syntax error
./wetterstation.sh: Zeile 198: get_DATA: Kommando nicht gefunden.
./wetterstation.sh: Zeile 326: debuging: Kommando nicht gefunden.
(standard_in) 1: syntax error
./wetterstation.sh: Zeile 198: get_DATA: Kommando nicht gefunden.
./wetterstation.sh: Zeile 326: debuging: Kommando nicht gefunden.

**Comment by SBorg2014** [comment]
Hi, ich weiß nicht wie oder warum, aber die wetterstation.sub ist im Windowsformat mit CRs hier gelandet.
Entweder nochmals die sub neu laden oder per `dos2unix wetterstation.sub` patchen (ggf. muss dos2unix mittels `sudo apt install dos2unix` nachinstalliert werden)

**Comment by schlaubstar** [comment]
Danke für die Info. Ich bin temporär zurück zur v2.0.16 und hab gerade eben nochmal das Update auf 2.0.17 gemacht => geht.
Das nächste mal schaue ich mir die Zeilenenden an, dann hätte ich das Problem schnell selbst erkannt und behoben. Vielen Dank

**Comment by SBorg2014** [comment]
Ich würde nur mal zu gerne wissen wo das herkommt. Das war vor zig Versionen schon mal, da direkt beim Shell-Skript. Ich schreibe das Ganze nur mittels "nano" direkt in der bash ;-)
