### ISSUE TITLE
Erweiterung: Influxdb2 hinzufügen (Skript + Statistik)

### ISSUE THREAD

**Issue by latzi0710** [SBorg2014/WLAN-Wetterstation#41]
Erweiterung der möglichen DB´s (hier influxdb2) sowohl im Skript als auch in der Statistik. Dies sollte mit `getHistory` bei der sendto-Anweisung möglich sein (siehe https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/3748)

**Comment by SBorg2014** [comment]
Habe/hatte ich ehrlich gesagt schon wieder vergessen...

**Comment by Rushmed** [comment]
Ich würde mich darüber auch riesig freuen.

**Comment by SpezialAgent** [comment]
Ich kann mich dem nur anschliessen. Ich bin vor 9 Monaten auf Influxdb2 umgestiegen und vermisse die Funktion stark. Bitte bitte bitte .....

**Comment by cornwallace** [comment]
+1

**Comment by schittl** [comment]
+1

**Comment by dadude86** [comment]
+1

**Comment by XxJooO** [comment]
+1

**Comment by SBorg2014** [comment]
Done in V3 👍
