### ISSUE TITLE
Solarenergie_Tag auf zwei Datenpunkte aufteilen

### ISSUE THREAD

**Issue by schlaubstar** [SBorg2014/WLAN-Wetterstation#43]
Hi, 
nach fast einem Jahr zufriedener Nutzung dieses schönen Projekts habe ich mal in meine InfluxDB geschaut und die Datenpunkte pro Measurement ausgewertet. The winner was: "Solarenergie_Tag" mit etwas über 500k Datenpunkten. 
Da der Wert bei jeder Messung steigt, erzeugt eigentlich jede Nachricht von der Wetterstation einen neuen Eintrag. 
Dabei interessiert ja nur der letzte Wert des Tages. 
Wäre es möglich, einen "neuen Datenpunkt" : SolarenergieVortrag_gesamt (oder so ähnlich) einzufügen, der einmalig/Tag, bei Deinen Mitternachtsverrechnungen mit dem Wert von Solarenergie_Tag beschrieben wird? Dann könnte man den sich ständig ändernden Datenpunkt einfach von der Aufzeichnung ausschließen und hätte trotzdem mit 365 Datenpunkten das jeweilige Tagesmaximum zum Aufzeichnen ? 

Vielen lieben Dank !

**Comment by SBorg2014** [comment]
Sorry, hat etwas gedauert. Das gibt es eigentlich schon und nennt sich"SolarEnergie Gestern" `javascript.0.Wetterstation.Info.Solarenergie_VorTag`. Da wird um 23:58 Uhr der heutige Gesamtwert einmalig gespeichert. Ist zwar dann genau genommen für 2 Minuten falsch, stimmt aber dann ab 0:00 Uhr ;)

**Comment by schlaubstar** [comment]
Ja besten Dank für die Info ! Da hab ich im "Datenpunktdickicht" diesen Punkt übersehen ! :-)
