### ISSUE TITLE
Zusatzesensor

### ISSUE THREAD

**Issue by serav993** [SBorg2014/WLAN-Wetterstation#44]
Erstmal Vielen Dank für das Projekt, echt eine tolle Arbeit.

Habe eine DNT WeatherScreen PRO.

Die Integration der Anlage hat soweit geklappt.
Nur leider bekomme ich den Zusatzsensor für Außen nicht integriert.

Der passt zu keiner im Script genannten Type.

Sensor:

Temp & Feuchte mit DCF77
DNT000005

Hat jemand zufällig eine gute Idee?

**Comment by SBorg2014** [comment]
Hi und danke.
Du kannst einfach mal alle DHT-Derivate mit Temp/Feuchte durchprobieren (falls nicht schon geschehen), müssten so um die drei Modelle sein, und/oder

- Service mittels `systemctl stop wetterstation` anhalten
- im Installationsverzeichnis `./wetterstation.sh --data` ausführen
- den Ausgabestring hier posten (zu Begin die Station-ID etc. aus-x-en)
- Service wieder starten `systemctl start wetterstation`

(für Mitleser: ja, ich lebe noch und melde mich [hoffentlich] demnächst mal wieder ;) )

**Comment by serav993** [comment]
Danke für die Antwort.
Ich hatte mir einfach die Sensoren durchgelesen und in der .config den DT40 und DT50 aktiviert weil sie der Beschreibung am nächsten kamen.
Konnte also über ausschlussverfahren den Sensor eingrenzen.
Jetzt kenne ich eine elegantere Variante.

Super Projekt nochmal und auch mit marginalen Programmierkenntnissen bekommt man das zum laufen. 
MfG

**Comment by SBorg2014** [comment]
Es kann sein, dass er ev. gar nicht gesendet wird, oder, was wahrscheinlicher ist, er bei den DNT-Sensoren anders benannt wurde. Üblicherweise lauten die "wh[XX]batt" im Datenstring (das ist mit der Grund warum es gleiche Sensoren von verschiedenen Herstellern im Projekt gibt und diese nicht unter einem Namen laufen).
Schau mal im String (s.o.) danach oder poste ihn hier.

**Comment by serav993** [comment]
Hat mit DT50 geklappt :)

**Comment by asturma** [comment]
Ich habe dieselbe Wetterstation und auch zusätzliche diese DNT000005 Sensoren.
Ich finde allerdings im .conf keine Möglichkeit DT50 festzulegen. Es gibt nur DP50. Datenpunkte habe ich angelegt, allerdings werden keine Werte übertragen. 
Was mache ich falsch?

Alle anderen Werte der Station werden übertragen. 
Danke für Tipps

**Comment by asturma** [comment]
Hallo, bräuchte bitte auch mal eure Hilfe

Ich habe dieselbe Wetterstation (DNT WeatherScreen PRO) und auch zusätzlich 2 dieser DNT000005 Sensoren.
Ich finde allerdings im .conf keine Möglichkeit DT50 festzulegen. Es gibt nur DP50. Datenpunkte habe ich angelegt, allerdings werden keine Werte übertragen.
Was mache ich falsch?

Mittels "./wetterstation.sh --data" sehe ich, dass im String die Daten (Temp und Luftfeuchte) als temp3/temp4 enthalten sind
"...&temp3f=55.6&humidity3=81&temp4f=71.1&humidity4=60...."

Alle anderen Werte der Station werden übertragen.
Danke für Tipps

**Comment by asturma** [comment]
Ich habe den Web- und SimpleAPI Adapter neu gestartet. Hat nicht geholfen. Danach den iobroker neu gestartet. Nach wie vor werden keine DP50 Datenpunkte befüllt :-(

**Comment by asturma** [comment]
Ich habe mal das Script gestoppt einmal im Debug-Modus ausgeführt, vielleicht hilft der Output weiter.
Interessanterweise schreibt es nach den ganzen Werten "Zusatzsensoren: Keine" -> siehe unten

---------  Start ----------
Messwerteblock: 22.38 16.88 4.61 16.88 64 44 4.34 7.24 116 965.93 965.93 0 0 24.409 92.202 237.490 630.28 6 25.04.2023%2013:10:59 EasyWeatherV1.6.5 temp3f 13.00 humidity3 81 temp4f 23.38 humidity4 57


Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

 Temperatur Innen               : 22.38 °C
 Temperatur Aussen              : 16.88 °C
 Taupunkt                       : 4.61 °C
 Gefühlte Temperatur            : 16.88 °C
 Luftfeuchte Innen              : 64 %
 Luftfeuchte Aussen             : 44 %
 Windgeschwindigkeit            : 4.34 km/h
 Windgeschwindigkeit 10min      :  km/h
 Windböengeschwindigkeit        : 7.24 km/h
 max. Windböe                   :  km/h
 Windrichtung                   : 116 °
 Windrichtung                   : OSO
 Windrichtung 10min             :  °
 Luftdruck absolut              : 965.93 hPa
 Luftdruck relativ              : 965.93 hPa
 Regenrate                      : 0 mm/h
 Regenstatus                    : kein Regen
 Regen seit Regenbeginn         :  mm
 Regen Stunde                   :  mm
 Regen Tag                      : 0 mm
 Regen Woche                    : 24.409 mm
 Regen Monat                    : 92.202 mm
 Regen Jahr                     : 237.490 mm
 Regen Gesamt                   :  mm
 Sonnenstrahlung                : 630.28 W/m²
 UV-Index                       : 6
 Zeitstempel                    : 25.04.2023 13:10:59
 Firmware                       : EasyWeatherV1.6.5
 Batteriestand:                 :
 Gateway-Modell                 :

Zusatzsensoren: keine

Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=22.38&........
---------  Ende -------------

**Comment by SBorg2014** [comment]
Leider hast du gerade da aufgehört wo es interessant wird ^^
Hast du bei der Anzahl in der "conf" zwei eingetragen? Dann müssen die sich auch als "temp1f" bzw. "temp2f" melden, denn genau die Bezeichnung erwartet das Skript. Wenn die sich nicht umbenennen lassen, musst du als Anzahl "4" eintragen (und auch per Javascript vier DPs/Sensoren anlegen lassen). Nr.1 und Nr.2 bleiben dann zwar leer, aber 3 und 4 liefern dann die Werte.

**Comment by asturma** [comment]
Irgendwo ist da der Wurm drinnen :-)
Ich habe jetzt auf 4 Sensoren erhöht und Datenpunkt 3 und 4 angelegt.
Servcei neu gestartet, SimpleAPI und Web Adapter neu gestartet, iobroker komplett neu gestartet. Nach wie vor keine Übertragung der Zusatzsensoren, weder bei 1 und 2, noch bei 3 und 4.

Hier noch der Rest des vorigen Auszugs:
----- Start----------------
Messwerteblock: 22.38 16.88 4.61 16.88 64 44 4.34 7.24 116 965.93 965.93 0 0 24.409 92.202 237.490 630.28 6 25.04.2023%2013:10:59 EasyWeatherV1.6.5 temp3f 13.00 humidity3 81 temp4f 23.38 humidity4 57


Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

 Temperatur Innen               : 22.38 °C
 Temperatur Aussen              : 16.88 °C
 Taupunkt                       : 4.61 °C
 Gefühlte Temperatur            : 16.88 °C
 Luftfeuchte Innen              : 64 %
 Luftfeuchte Aussen             : 44 %
 Windgeschwindigkeit            : 4.34 km/h
 Windgeschwindigkeit 10min      :  km/h
 Windböengeschwindigkeit        : 7.24 km/h
 max. Windböe                   :  km/h
 Windrichtung                   : 116 °
 Windrichtung                   : OSO
 Windrichtung 10min             :  °
 Luftdruck absolut              : 965.93 hPa
 Luftdruck relativ              : 965.93 hPa
 Regenrate                      : 0 mm/h
 Regenstatus                    : kein Regen
 Regen seit Regenbeginn         :  mm
 Regen Stunde                   :  mm
 Regen Tag                      : 0 mm
 Regen Woche                    : 24.409 mm
 Regen Monat                    : 92.202 mm
 Regen Jahr                     : 237.490 mm
 Regen Gesamt                   :  mm
 Sonnenstrahlung                : 630.28 W/m²
 UV-Index                       : 6
 Zeitstempel                    : 25.04.2023 13:10:59
 Firmware                       : EasyWeatherV1.6.5
 Batteriestand:                 :
 Gateway-Modell                 :

Zusatzsensoren: keine


Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=22.38&javascript.0.Wetterstation.Aussentemperatur=16.88&javascript.0.Wetterstation.Taupunkt=4.61&javascript.0.Wetterstation.Gefuehlte_Temperatur=16.88&javascript.0.Wetterstation.Innenfeuchtigkeit=64&javascript.0.Wetterstation.Aussenfeuchtigkeit=44&javascript.0.Wetterstation.Wind=4.34&javascript.0.Wetterstation.Wind_max=7.24&javascript.0.Wetterstation.Windrichtung=116&javascript.0.Wetterstation.Druck_absolut=965.93&javascript.0.Wetterstation.Druck_relativ=965.93&javascript.0.Wetterstation.Regenrate=0&javascript.0.Wetterstation.Regen_Tag=0&javascript.0.Wetterstation.Regen_Woche=24.409&javascript.0.Wetterstation.Regen_Monat=92.202&javascript.0.Wetterstation.Regen_Jahr=237.490&javascript.0.Wetterstation.Sonnenstrahlung=630.28&javascript.0.Wetterstation.UV_Index=6&javascript.0.Wetterstation.Zeitstempel=25.04.2023%2013:10:59&javascript.0.Wetterstation.Info.FW_Version=EasyWeatherV1.6.5&javascript.0.Wetterstation.Regenstatus=kein Regen&javascript.0.Wetterstation.UV_Belastung=hoch&javascript.0.Wetterstation.Windrichtung_Text=OSO&javascript.0.Wetterstation.Info.Hitzeindex=


DATA von Wetterstation:
GET /weatherstation/updateweatherstation.php?ID=xxxxxx&PASSWORD=xxxxxx&indoortempf=72.3&tempf=62.4&dewptf=40.3&windchillf=62.4&indoorhumidity=64&humidity=44&windspeedmph=2.7&windgustmph=4.5&winddir=116&absbaromin=28.524&baromin=28.524&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.961&monthlyrainin=3.630&yearlyrainin=9.350&solarradiation=630.28&UV=6&temp3f=55.4&humidity3=81&temp4f=74.1&humidity4=57&dateutc=2023-04-25%2011:10:59&softwaretype=EasyWeatherV1.6.5&action=updateraw&realtime=1&rtfreq=5 HTTP/1.1


Debug VAR:
 Installationsverzeichnis: /home/pi/wetterstation
 IPP: 10.0.0.x:8087     WS_PORT: 1080           WS_POLL: 30             PRE_DP: javascript.0.Wetterstation
 WEB: HTTP              WS_PROT: Wunderground

Zusatzsensoren:
 DP10/35/40/50/60/70/100/200/250/300: 0 | 0 | 0 | 2 | 0 | 0 | 0 | 0 | 0 | 0
 WH31: 0 || WS90: 0
 Bresser: 7009999 [0]

Script-Version: V3.0.0  Config-Version: V3.0.0  Sub-Version: V3.0.0
--------- Ende -------------

**Comment by asturma** [comment]
Jetzt läuft es dank Umstellung auf Ecowitt. Habe in der Anleitung die erste Variante (Wunderground) genommen, Auswirkungen waren nicht bekannt :-)
Vielen vielen Dank für die Hilfe
