### ISSUE TITLE
Berechnung Wolkenbasis

### ISSUE THREAD

**Issue by latzi0710** [SBorg2014/WLAN-Wetterstation#46]
Bei negativen Temp.-werten tritt ein Fehler in der Berechnung der Wolkenbasis auf, siehe
https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/4308?_=1670910868818

Bitte um Anpassung der .sub Datei. 👍

**Comment by SBorg2014** [comment]
fixed in V2.20.0
