### ISSUE TITLE
Problem Wetterwarnungen

### ISSUE THREAD

**Issue by viper4gh** [SBorg2014/WLAN-Wetterstation#47]
Es scheint, dass der Vergleich zwischen Taupunkt und Außentemperatur falsch herum ist.
In der Funktion do_Wetterwarnung():
`if [ 1 -eq "$(echo "${MESSWERTE[2]} < ${MESSWERTE[1]}" | bc -l)" ]; then`
Wobei 
MESSWERTE[1] = Außentemperatur
MESSWERTE[1] = Taupunkt
Dieses statement ist true, wenn der Taupunkt niedriger ist als die Außentemperatur.
Wenn ich es richtig verstanden habe, muss der Taupunkt aber über der Außentemperatur liegen, damit es Tau/Nebel oder Reif gibt.
D.h. richtig wäre dann:
`if [ 1 -eq "$(echo "${MESSWERTE[1]} < ${MESSWERTE[2]}" | bc -l)" ]; then`

Mir ist es deshalb aufgefallen, weil wir gerade dauerhaft Temperaturen unter 0,5°C haben, was das Kriterium für Reif ist, und bei mir dauerhaft Reif ausgegeben wird, obwohl der Taupunkt die ganze Zeit unter der Außentemperatur liegt.

**Comment by SBorg2014** [comment]
Gelesen und dann wohl beim programmieren vergessen, vertauscht...
Danke :)

**Comment by SBorg2014** [comment]
fixed in V2.20.0
