### ISSUE TITLE
wetterstation.sh bringt syntax error

### ISSUE THREAD

**Issue by CKMartens** [SBorg2014/WLAN-Wetterstation#49]
Ich habe die ELV WS980WiFi Wetterstation eingebunden. Beim Aufruf von ./wetterstation.sh --debug werden einige Daten an ioBroker gesendet, aber am Anfang des Skripts kommen Fehlermeldungen syntax error
![image](https://user-images.githubusercontent.com/19702758/209802302-541b38ba-46cb-45a9-96e1-8efda2db9f01.png)

Bei Abfrage des Service mit systemctl status wetterstation erscheint auch das das Skript die Melungen syntax error bringt
![image](https://user-images.githubusercontent.com/19702758/209802538-26d69e97-ef41-4f50-be62-a47c24ebc41f.png)

**Comment by SBorg2014** [comment]
"...illegal charakter: :"
Da bekommt er offenbar von der ELV einen Doppelpunkt, der da nicht erwartet bzw. nicht sein sollte.
Ich bin nicht mehr so mit der ELV bewandert, da die Nutzerzahl mehr als überschaubar ist, aber du nutzt anscheinend "Wunderground" als Format? Hat das einen bestimmten Grund? Es sollte damit natürlich auch funktionieren, aber ev. haben sie da auch was am Datenformat geändert, was bisher nicht auffiel, da kaum noch jemand mittels WU unterwegs ist. "Ecowitt" liefert einfach (unter Umständen, zwangsläufig nicht immer) mehr Daten.
Ansonsten kannst du den Service auch mal stoppen und dann mittels `./wetterstation.sh --data` deinen Datenstring hier posten (Userdaten natürlich vorher unkenntlich machen ;) ).
