### ISSUE TITLE
Update Prozess

### ISSUE THREAD

**Issue by fabiankrauss** [SBorg2014/WLAN-Wetterstation#5]
Hallo es wäre doch klasse in dem Wiki eine kurze Einleitung einzubinden, welche Dateien ich tauschen muss, um auf die neue Variante upzudaten.

Habe vor wenigen Tagen V1.2.0 bei mir installiert.
Kann ich meine Config weiter verwenden? Muss ich alle Dateien, oder nur bestimmte. Denke auch das man das DP-Skript neu reinkopieren und ausführen muss. :)

Da wäre etwas Info zu doch klasse?

Danke im Voraus!

**Comment by SBorg2014** [comment]
Hi,
ja, die Idee ist nicht schlecht. Kam mir einfach nicht in den Sinn, da dass Ganze aus dem ioB-Forum entstand und ich dort alles zu den Versionen poste ([Thread im ioBroker-Forum](https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation)). Dabei habe ich kpl. aus den Augen verloren, dass der ein oder andere ja auch per diversen Suchmaschinen direkt hier landen könnte.
Danke für den Hinweis und füge ich zeitnah dem Wiki noch hinzu.
Pauschal kann man aber sagen: neue Versionsnummer einer Datei = muss ersetzt werden
Die haben nicht umsonst Versionsnummern. Für den aktuellen Fix in der V1.3.1 genügt bspw. die "sh" zu tauschen, der Rest verbleibt hier bei 1.3.0, da nur eine Änderung in der "sh" nötig war. "js" immer dann wenn neue DPs hinzukommen (dann bekommt sie auch eine höhere Versionsnummer) und die "conf" nach Möglichkeit nicht so oft, da hier die User-Einstellungen liegen. Deswegen hatte ich es auch vor x Versionen extra getrennt, nur kamen bisher immer noch User-Wünsche hinzu, die dann schlussendlich doch immer eine Änderung darin notwendig werden ließen.

**Comment by SBorg2014** [comment]
Erledigt und daher "closed"
[Seite in der Wiki](https://github.com/SBorg2014/WLAN-Wetterstation/wiki/Update-auf-eine-neue-Version)
