### ISSUE TITLE
Konflikt mit WeeWx

### ISSUE THREAD

**Issue by jernst01** [SBorg2014/WLAN-Wetterstation#50]
Hallo,
habe die WLAN Wetterstation auf einem Raspberry Pi4 mit einer Frogitt HP1000SE-PRO_Pro_V1.7.8 auf IOBroker zum Laufen gebracht. Sieht richtig gut aus.
ABER ... auf dem gleichen Raspberry läuft WeeWX, genauer gesagt lief. Es scheint da einen Konflikt zu geben, der WeeWx hindert. Könnte es ein Konflikt mit den Ports sein? WeeWx / der Interpreter für die Froggit hat die Daten über den Port 8000 ausgelesen. Hatte ich diesen Port auch in WLAN- Wetterstation eingestellt bekam ich die Info, daß die Verbindung belegt sein. Dann habe ich den Port in WLAN Wetterstation und der Frogitt geändert und die Verbindung zum IOBroker ging.
Unabhängig davon hängt aber WeeWx im main loop. Ist das Problem bekannt?
Hier kurz der Status von WeeWX:

> pi@raspberrypi:~ $ systemctl status weewx
* weewx.service - LSB: weewx weather system
     Loaded: loaded (/etc/init.d/weewx; generated)
     Active: active (running) since Thu 2022-12-29 07:02:59 CET; 22min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 454 ExecStart=/etc/init.d/weewx start (code=exited, status=0/SUCCESS)
      Tasks: 3 (limit: 4915)
        CPU: 1.249s
     CGroup: /system.slice/weewx.service
             `-680 python3 /usr/share/weewx/weewxd --daemon --pidfile=/var/run/weewx.pid /etc/weewx/weewx.conf

Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.restx: PWSweather: Posting not enabled.
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.restx: CWOP: Posting not enabled.
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.restx: WOW: Posting not enabled.
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.restx: AWEKAS: Data will be uploaded for user jernst
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.engine: 'pyephem' detected, extended almanac data is available
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO __main__: Starting up weewx version 4.9.1
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.manager: Starting backfill of daily summaries
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.manager: Daily summaries up to date
Dez 29 07:03:00 raspberrypi python3[680]: weewx[680] INFO weewx.engine: Starting main packet loop.

Und hier der Statuns von Wetterstation:

pi@raspberrypi:~ $ systemctl status wetterstation
* wetterstation.service - Service für ioBroker Wetterstation
     Loaded: loaded (/etc/systemd/system/wetterstation.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-29 07:02:55 CET; 30min ago
   Main PID: 459 (wetterstation.s)
      Tasks: 5 (limit: 4915)
        CPU: 2min 5.455s
     CGroup: /system.slice/wetterstation.service
             |-  459 /bin/bash /home/pi/wetterstation/wetterstation.sh
             |-17524 /bin/bash /home/pi/wetterstation/wetterstation.sh
             |-17525 timeout 66 nc -nlvw 1 -p 2242
             |-17526 tail -1
             `-17527 nc -nlvw 1 -p 2242

Dez 29 07:02:55 raspberrypi systemd[1]: Started Service für ioBroker Wetterstation.
Dez 29 07:02:56 raspberrypi wetterstation.sh[550]: nc: connect to 192.168.222.172 port 8087 (tcp) failed: Network is unreachable
Dez 29 07:03:41 raspberrypi wetterstation.sh[974]: nc: connect to 192.168.222.172 port 8087 (tcp) failed: Connection refused
Dez 29 07:04:11 raspberrypi wetterstation.sh[1093]: nc: connect to 192.168.222.172 port 8087 (tcp) failed: Connection refused
Dez 29 07:04:41 raspberrypi wetterstation.sh[1254]: nc: connect to 192.168.222.172 port 8087 (tcp) failed: Connection refused
Dez 29 07:05:11 raspberrypi wetterstation.sh[1319]: Connection to 192.168.222.172 8087 port [tcp/*] succeeded!

Danke
Jürgen

**Comment by SBorg2014** [comment]
Hallo Jürgen,
zu deinem Leidwesen ist es leider so wie du bereits vermutet hast. Pro Service ein unterschiedlicher Port. Das sind die "Empfänger". Der "Sender" (=Display oder Gateway) kann aber nur auf einem Port senden, ist also eine entweder/oder Situation.
Man bräuchte in diesem Fall also eine Art "Software-Splitter", der Daten an Port X entgegen nimmt und diese dann an Port Y (zB. WeeWX) und Port Z (zB. das Shell-Skript) weiterleitet.  Beim Portforwarding ist mir dies bei bekannter Software aber nur für einen Port bekannt, also empfange IP X und Port X und schicke es dann an IP Y und Port Y.
Pauschal könnte ich auch das empfangene Datenpaket an WeeWX weiter reichen (ich mache also den "Software-Splitter"), allerdings kenne ich mich mit WeeWX mal genau "Null" aus, so dass dies wohl eher in einer Tageaktion als Stundenaktion enden wird. Kein pauschales Nein meinerseits, aber aktuell zeitlich einfach nicht umsetzbar.

...ich habe eben WeeWX mal überflogen. Im Grunde hast du doch eine funktionsfähige Konstellation von Wetterstation und WeeWX (ohne Shell-Skript). Dann müsste, wenn das Shell-Skript funktionsfähig läuft (zB. wie oben auf Port 2242) und WeeWX nun zB. auf Port 8000 läuft, es genügen wenn ich das empfangene RAW-Datenpaket 1:1 wieder an Port 8000 schicke.

**Comment by jernst01** [comment]
Hört sich erstmal logisch an. Was mich jedoch stutzen läßt, ist der Umstand, daß egal in welchem Programm ich den Richtigen oder falsche Port eintrage (ich hatte zum Anfang die 1080 übernommen, WeeWx im mainloop hängen bleibt.
 Ich werde es einfach, kostengünstig, nervenschonend und systembezogen Updatsicher auf 2 unterschiedlichen Raspberrys installieren. So kann sich jede Installation über ihre Hardware am Port XY "bedienen".

Ansonsten ist Deine Lösung richtig gut. Großes Kompliment!!!!!!
Gruß
Jürgen

**Comment by jernst01** [comment]
Sorry eins hatte ich noch vergessen zu fragen, gibt es ein Workaround für die komplette Deinstallation von WLAN-Wetterstation?
Danke
Jürgen

**Comment by SBorg2014** [comment]
Danke für die Blumen, da stecken auch "einige" Stunden drin ;)
Leider muss ich dir aber schon wieder einen Dämpfer verpassen, denn zwei PIs lösen dein Problem so auch nicht, denn deine Station kann nur an _eine_ IP und _einen_ Port senden. Zwei PIs = zwei IPs
Also wieder nur PI # 1 mit WeeWx **oder** PI  # 2 mit Shell-Skript...

Es wäre ja vermessen zu sagen niemand deinstalliert es, deswegen gibt es keine Erklärung, der Grund ist aber ziemlich einfach: schlichtweg vergessen. Da ich mich aus der Shell nicht selbst löschen kann, wird es auch keine Routine geben können.
Da ich aber nichts am System verändere genügt es Service stoppen, die Service-Datei und das ganze Verezeichnis (oder die wetterstation.*-Dateien einzeln) löschen. Kommt aber in die WiKi und danke für den "Hinweis" ;)

**Comment by jernst01** [comment]
Gerne, dann muß ich mal viel nachdenken wie ich das löse. Aber Neujahr sei Dank, ich werde wohl Weewx, deren Daten alle auf meiner Webseite sind zum 01.01.2023 gegen Deine Lösung mit IoBroker ersetzen und mir dann all die Statistiken selber "backen". Mit ECharts sind die Daten dann auch gespeichert und können schön in Graphen dargestellt werden.
Vielen Dank erst einmal und einen guten Rutsch.
Jürgen

**Comment by SBorg2014** [comment]
Danke, dir, und allen Mitlesern natürlich auch, ebenso.

Wesentlich flexibler wärst du aber IMO per Influx loggen und mittels Grafana darstellen (siehe zB. Startseite. Das sind alles einzelne Widgets. Diese lassen sich dann auch easy in der VIS oder auf einer Website anzeigen). Influx und Grafana nutzen so gut wie alle Nutzer.

**Comment by mendikant** [comment]
Bin hier gerade drüber gestolpert. Ich mache es folgendermaßen: 
Weewx fragt bei mir aktiv bei der Wetterstation an, die wetterstation.sh lauscht auf dem Port, was die ecowitt schickt.
