### ISSUE TITLE
GW 2000 Datenpunkte unvollständig

### ISSUE THREAD

**Issue by mendikant** [SBorg2014/WLAN-Wetterstation#51]
Hi!

Ich nutze eine GW200 mit einem WS90. Die Datenpunkte für Regen unter WS90 werden befüllt. Die unter Wetterstation nicht. Zwei Beispiele: 
javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge wird befüllt. javascript.0.Wetterstation.Regen_Jahr dagegen nicht. 

Abgeholt werden die Informationen: 

Connection to 192.168.178.106 8087 port [tcp/*] succeeded!

/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
/home/wetter/wetterstation/wetterstation.sub: Zeile 364: [: : Ganzzahliger Ausdruck erwartet.
[
  {
    "id": "javascript.0.Wetterstation.Innentemperatur",
    "val": 17.8
  },
  {
    "id": "javascript.0.Wetterstation.Aussentemperatur",
    "val": 8
  },
  {
    "id": "javascript.0.Wetterstation.Taupunkt",
    "val": 4.77
  },
  {
    "id": "javascript.0.Wetterstation.Gefuehlte_Temperatur",
    "val": 8
  },
  {
    "id": "javascript.0.Wetterstation.Innenfeuchtigkeit",
    "val": 50
  },
  {
    "id": "javascript.0.Wetterstation.Aussenfeuchtigkeit",
    "val": 80
  },
  {
    "id": "javascript.0.Wetterstation.Wind",
    "val": 4.31
  },
  {
    "id": "javascript.0.Wetterstation.Wind_max",
    "val": 7.91
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung",
    "val": 125
  },
  {
    "id": "javascript.0.Wetterstation.Druck_absolut",
    "val": 990.58
  },
  {
    "id": "javascript.0.Wetterstation.Druck_relativ",
    "val": 990.58
  },
  {
    "id": "javascript.0.Wetterstation.Sonnenstrahlung",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.UV_Index",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.Zeitstempel",
    "val": "13.01.2023 07:12:43"
  },
  {
    "id": "javascript.0.Wetterstation.Info.FW_Version",
    "val": "GW2000A_V2.2.0"
  },
  {
    "id": "javascript.0.Wetterstation.Windboeen_max",
    "val": 16.91
  },
  {
    "id": "javascript.0.Wetterstation.Info.Wetterstation_Gateway",
    "val": "GW2000A"
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.aktuelle_Regenrate",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.aktuelle_Regenmenge",
    "val": 16.103
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.stuendliche_Regenmenge",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.taegliche_Regenmenge",
    "val": 0.609
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.woechentliche_Regenmenge",
    "val": 17.805
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.monatliche_Regenmenge",
    "val": 19.71
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge",
    "val": 19.71
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Spannung_GoldCap",
    "val": 2.4
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Firmwareversion",
    "val": 126
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Batterie",
    "val": 3.06
  },
  {
    "id": "javascript.0.Wetterstation.Regenstatus",
    "val": ""
  },
  {
    "id": "javascript.0.Wetterstation.UV_Belastung",
    "val": "keine"
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung_Text",
    "val": "SO"
  },
  {
    "id": "javascript.0.Wetterstation.Info.Hitzeindex",
    "val": ""
  }
]

Messwerteblock: 17.80 8.00 4.77 8.00 50 80 4.31 7.91 125 990.58 990.58 0.00 0 13.01.2023%2007:12:43 GW2000A_V2.2.0 16.91 GW2000A rrain_piezo 0 erain_piezo 16.103 hrain_piezo 0 drain_piezo .609 wrain_piezo 17.805 mrain_piezo 19.710 yrain_piezo 19.710 ws90cap_volt 2.4 ws90_ver 126 wh90batt 3.06

Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

Temperatur Innen	: 17.80 °C
Temperatur Aussen	: 8.00 °C
Taupunkt		: 4.77 °C
Gefühlte Temperatur	: 8.00 °C
Luftfeuchte Innen	: 50 %
Luftfeuchte Aussen	: 80 %
Windgeschwindigkeit	: 4.31 km/h
Windgeschwindigkeit 10min	:  km/h
Windböengeschwindigkeit	: 7.91 km/h
max. Windböe		: 16.91 km/h
Windrichtung		: 125 °
Windrichtung		: SO
Windrichtung 10min	:  °
Luftdruck absolut	: 990.58 hPa
Luftdruck relativ	: 990.58 hPa
Regenrate		:  mm/h
Regenstatus		: 
Regen seit Regenbeginn	:  mm
Regen Stunde		:  mm
Regen Tag		:  mm
Regen Woche		:  mm
Regen Monat		:  mm
Regen Jahr		:  mm
Regen Gesamt		:  mm
Sonnenstrahlung		: 0.00 W/m²
UV-Index		: 0
Zeitstempel		: 13.01.2023 07:12:43
Firmware		: GW2000A_V2.2.0
Batteriestand:		: 
Gateway-Modell		: GW2000A

Zusatzsensoren:

  rrain_piezo                        : 0
  erain_piezo                        : 16.103
  hrain_piezo                        : 0
  drain_piezo                        : .609
  wrain_piezo                        : 17.805
  mrain_piezo                        : 19.710
  yrain_piezo                        : 19.710
  ws90cap_volt                        : 2.4
  ws90_ver                        : 126
  wh90batt                        : 3.06

Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=17.80&javascript.0.Wetterstation.Aussentemperatur=8.00&javascript.0.Wetterstation.Taupunkt=4.77&javascript.0.Wetterstation.Gefuehlte_Temperatur=8.00&javascript.0.Wetterstation.Innenfeuchtigkeit=50&javascript.0.Wetterstation.Aussenfeuchtigkeit=80&javascript.0.Wetterstation.Wind=4.31&javascript.0.Wetterstation.Wind_max=7.91&javascript.0.Wetterstation.Windrichtung=125&javascript.0.Wetterstation.Druck_absolut=990.58&javascript.0.Wetterstation.Druck_relativ=990.58&javascript.0.Wetterstation.Sonnenstrahlung=0.00&javascript.0.Wetterstation.UV_Index=0&javascript.0.Wetterstation.Zeitstempel=13.01.2023%2007:12:43&javascript.0.Wetterstation.Info.FW_Version=GW2000A_V2.2.0&javascript.0.Wetterstation.Windboeen_max=16.91&javascript.0.Wetterstation.Info.Wetterstation_Gateway=GW2000A&javascript.0.Wetterstation.WS90.1.aktuelle_Regenrate=0&javascript.0.Wetterstation.WS90.1.aktuelle_Regenmenge=16.103&javascript.0.Wetterstation.WS90.1.stuendliche_Regenmenge=0&javascript.0.Wetterstation.WS90.1.taegliche_Regenmenge=.609&javascript.0.Wetterstation.WS90.1.woechentliche_Regenmenge=17.805&javascript.0.Wetterstation.WS90.1.monatliche_Regenmenge=19.710&javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge=19.710&javascript.0.Wetterstation.WS90.1.Spannung_GoldCap=2.4&javascript.0.Wetterstation.WS90.1.Firmwareversion=126&javascript.0.Wetterstation.WS90.1.Batterie=3.06&javascript.0.Wetterstation.Regenstatus=&javascript.0.Wetterstation.UV_Belastung=keine&javascript.0.Wetterstation.Windrichtung_Text=SO&javascript.0.Wetterstation.Info.Hitzeindex=

DATA von Wetterstation:
PASSKEY=xxxxxx&stationtype=GW2000A_V2.2.0&runtime=753417&dateutc=2023-01-13+06:12:43&tempinf=64.04&humidityin=50&baromrelin=29.252&baromabsin=29.252&tempf=46.40&humidity=80&winddir=125&windspeedmph=2.68&windgustmph=4.92&maxdailygust=10.51&solarradiation=0.00&uv=0&rrain_piezo=0.000&erain_piezo=0.634&hrain_piezo=0.000&drain_piezo=0.024&wrain_piezo=0.701&mrain_piezo=0.776&yrain_piezo=0.776&ws90cap_volt=2.4&ws90_ver=126&wh90batt=3.06&freq=868M&model=GW2000A

Debug VAR:
 Installationsverzeichnis: /home/wetter/wetterstation
 IPP: 192.168.178.106:8087	WS_PORT: 1080		WS_POLL: 30		PRE_DP: javascript.0.Wetterstation
 WEB: HTTP		WS_PROT: Ecowitt

Zusatzsensoren:
 DP10/35/40/50/60/70/100/200/250/300: 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 
 WH31: 0 || WS90: 1

Script-Version: V2.20.0	Config-Version: V2.20.0	Sub-Version: V2.20.0

Wenn ich noch mehr Infos liefern kann, gerne.

**Comment by SBorg2014** [comment]
Hi,
das ist auch mehr oder minder "normal", denn die Daten unter "Wetterstation" kommen per Außeneinheit auf das Display/Gateway. Beim "Wittboy" ist dies etwas anders, da sich dieser wie ein Zusatzsensor verhält. Deswegen kommen beim Start auch die Fehlermeldungen, da er für die Regenmenge keine Werte vom Wettermast erhält und alles was Regen betrifft beleibt leer.

Das ist im Ursprungskonzept nicht vorgesehen, da es vor 4 Jahren zuerst nur den Mast und Display gab, dann kamen die Gateways und Zusatzsensoren hinzu. Mit dem Wittboy kann man nun auch den Wettermast weglassen...

Muss ich ändern ;)

**Comment by mendikant** [comment]
Wenn ich was an Infos liefern oder irgendeinen Zwischenstand testen soll, gib gerne Bescheid...

**Comment by SBorg2014** [comment]
Die aktuelle Beta V2.21.0 testen ;)
https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/4354

...müsste damit funktionieren, aber ohne Hardware leider auch kein Test meinerseits...

**Comment by mendikant** [comment]
Done. Sieht gut aus. Damit müsste ich dann jetzt auch Opensensemap füttern können... 
Hier ein Output:

/wetterstation.sh
Connection to 192.168.178.106 8087 port [tcp/*] succeeded!
[
  {
    "id": "javascript.0.Wetterstation.Innentemperatur",
    "val": 18.4
  },
  {
    "id": "javascript.0.Wetterstation.Aussentemperatur",
    "val": 7.7
  },
  {
    "id": "javascript.0.Wetterstation.Taupunkt",
    "val": 5.68
  },
  {
    "id": "javascript.0.Wetterstation.Gefuehlte_Temperatur",
    "val": 7.7
  },
  {
    "id": "javascript.0.Wetterstation.Innenfeuchtigkeit",
    "val": 47
  },
  {
    "id": "javascript.0.Wetterstation.Aussenfeuchtigkeit",
    "val": 87
  },
  {
    "id": "javascript.0.Wetterstation.Wind",
    "val": 4.68
  },
  {
    "id": "javascript.0.Wetterstation.Wind_max",
    "val": 14.75
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung",
    "val": 20
  },
  {
    "id": "javascript.0.Wetterstation.Druck_absolut",
    "val": 994.78
  },
  {
    "id": "javascript.0.Wetterstation.Druck_relativ",
    "val": 994.78
  },
  {
    "id": "javascript.0.Wetterstation.Regenrate",
    "val": 1.193
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Tag",
    "val": 1.905
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Woche",
    "val": 19.1
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Monat",
    "val": 21.005
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Jahr",
    "val": 21.005
  },
  {
    "id": "javascript.0.Wetterstation.Sonnenstrahlung",
    "val": 108.05
  },
  {
    "id": "javascript.0.Wetterstation.UV_Index",
    "val": 1
  },
  {
    "id": "javascript.0.Wetterstation.Zeitstempel",
    "val": "13.01.2023 15:19:56"
  },
  {
    "id": "javascript.0.Wetterstation.Info.FW_Version",
    "val": "GW2000A_V2.2.0"
  },
  {
    "id": "javascript.0.Wetterstation.Windboeen_max",
    "val": 29.51
  },
  {
    "id": "javascript.0.Wetterstation.Info.Wetterstation_Gateway",
    "val": "GW2000A"
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.aktuelle_Regenrate",
    "val": 1.193
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.aktuelle_Regenmenge",
    "val": 17.399
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.stuendliche_Regenmenge",
    "val": 0.609
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.taegliche_Regenmenge",
    "val": 1.905
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.woechentliche_Regenmenge",
    "val": 19.1
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.monatliche_Regenmenge",
    "val": 21.005
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge",
    "val": 21.005
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Spannung_GoldCap",
    "val": 2.9
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Firmwareversion",
    "val": 126
  },
  {
    "id": "javascript.0.Wetterstation.WS90.1.Batterie",
    "val": 3.08
  },
  {
    "id": "javascript.0.Wetterstation.Regenstatus",
    "val": "leichter Regen"
  },
  {
    "id": "javascript.0.Wetterstation.UV_Belastung",
    "val": "gering"
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung_Text",
    "val": "NNO"
  },
  {
    "id": "javascript.0.Wetterstation.Info.Hitzeindex",
    "val": ""
  }
]

Messwerteblock: 18.40 7.70 5.68 7.70 47 87 4.68 14.75 20 994.78 994.78 1.193 1.905 19.100 21.005 21.005 108.05 1 13.01.2023%2015:19:56 GW2000A_V2.2.0 29.51 GW2000A rrain_piezo 1.193 erain_piezo 17.399 hrain_piezo .609 drain_piezo 1.905 wrain_piezo 19.100 mrain_piezo 21.005 yrain_piezo 21.005 ws90cap_volt 2.9 ws90_ver 126 wh90batt 3.08


Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

Temperatur Innen	: 18.40 °C
Temperatur Aussen	: 7.70 °C
Taupunkt		: 5.68 °C
Gefühlte Temperatur	: 7.70 °C
Luftfeuchte Innen	: 47 %
Luftfeuchte Aussen	: 87 %
Windgeschwindigkeit	: 4.68 km/h
Windgeschwindigkeit 10min	:  km/h
Windböengeschwindigkeit	: 14.75 km/h
max. Windböe		: 29.51 km/h
Windrichtung		: 20 °
Windrichtung		: NNO
Windrichtung 10min	:  °
Luftdruck absolut	: 994.78 hPa
Luftdruck relativ	: 994.78 hPa
Regenrate		: 1.193 mm/h
Regenstatus		: leichter Regen
Regen seit Regenbeginn	:  mm
Regen Stunde		:  mm
Regen Tag		: 1.905 mm
Regen Woche		: 19.100 mm
Regen Monat		: 21.005 mm
Regen Jahr		: 21.005 mm
Regen Gesamt		:  mm
Sonnenstrahlung		: 108.05 W/m²
UV-Index		: 1
Zeitstempel		: 13.01.2023 15:19:56
Firmware		: GW2000A_V2.2.0
Batteriestand:		: 
Gateway-Modell		: GW2000A

Zusatzsensoren:

  rrain_piezo                        : 1.193
  erain_piezo                        : 17.399
  hrain_piezo                        : .609
  drain_piezo                        : 1.905
  wrain_piezo                        : 19.100
  mrain_piezo                        : 21.005
  yrain_piezo                        : 21.005
  ws90cap_volt                        : 2.9
  ws90_ver                        : 126
  wh90batt                        : 3.08


Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=18.40&javascript.0.Wetterstation.Aussentemperatur=7.70&javascript.0.Wetterstation.Taupunkt=5.68&javascript.0.Wetterstation.Gefuehlte_Temperatur=7.70&javascript.0.Wetterstation.Innenfeuchtigkeit=47&javascript.0.Wetterstation.Aussenfeuchtigkeit=87&javascript.0.Wetterstation.Wind=4.68&javascript.0.Wetterstation.Wind_max=14.75&javascript.0.Wetterstation.Windrichtung=20&javascript.0.Wetterstation.Druck_absolut=994.78&javascript.0.Wetterstation.Druck_relativ=994.78&javascript.0.Wetterstation.Regenrate=1.193&javascript.0.Wetterstation.Regen_Tag=1.905&javascript.0.Wetterstation.Regen_Woche=19.100&javascript.0.Wetterstation.Regen_Monat=21.005&javascript.0.Wetterstation.Regen_Jahr=21.005&javascript.0.Wetterstation.Sonnenstrahlung=108.05&javascript.0.Wetterstation.UV_Index=1&javascript.0.Wetterstation.Zeitstempel=13.01.2023%2015:19:56&javascript.0.Wetterstation.Info.FW_Version=GW2000A_V2.2.0&javascript.0.Wetterstation.Windboeen_max=29.51&javascript.0.Wetterstation.Info.Wetterstation_Gateway=GW2000A&javascript.0.Wetterstation.WS90.1.aktuelle_Regenrate=1.193&javascript.0.Wetterstation.WS90.1.aktuelle_Regenmenge=17.399&javascript.0.Wetterstation.WS90.1.stuendliche_Regenmenge=.609&javascript.0.Wetterstation.WS90.1.taegliche_Regenmenge=1.905&javascript.0.Wetterstation.WS90.1.woechentliche_Regenmenge=19.100&javascript.0.Wetterstation.WS90.1.monatliche_Regenmenge=21.005&javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge=21.005&javascript.0.Wetterstation.WS90.1.Spannung_GoldCap=2.9&javascript.0.Wetterstation.WS90.1.Firmwareversion=126&javascript.0.Wetterstation.WS90.1.Batterie=3.08&javascript.0.Wetterstation.Regenstatus=leichter Regen&javascript.0.Wetterstation.UV_Belastung=gering&javascript.0.Wetterstation.Windrichtung_Text=NNO&javascript.0.Wetterstation.Info.Hitzeindex=


DATA von Wetterstation:
PASSKEY=xxxxxx&stationtype=GW2000A_V2.2.0&runtime=782650&dateutc=2023-01-13+14:19:56&tempinf=65.12&humidityin=47&baromrelin=29.376&baromabsin=29.376&tempf=45.86&humidity=87&winddir=20&windspeedmph=2.91&windgustmph=9.17&maxdailygust=18.34&solarradiation=108.05&uv=1&rrain_piezo=0.047&erain_piezo=0.685&hrain_piezo=0.024&drain_piezo=0.075&wrain_piezo=0.752&mrain_piezo=0.827&yrain_piezo=0.827&ws90cap_volt=2.9&ws90_ver=126&wh90batt=3.08&freq=868M&model=GW2000A


Debug VAR:
 Installationsverzeichnis: /home/wetter/wetterstation
 IPP: 192.168.178.106:8087	WS_PORT: 1080		WS_POLL: 30		PRE_DP: javascript.0.Wetterstation
 WEB: HTTP		WS_PROT: Ecowitt

Zusatzsensoren:
 DP10/35/40/50/60/70/100/200/250/300: 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 
 WH31: 0 || WS90: 1

Script-Version: V2.21.0	Config-Version: V2.21.0	Sub-Version: V2.21.0

**Comment by SBorg2014** [comment]
Jupp, sieht gut aus, würde sagen *fixed* und keinen Fipptehler eingebaut 😉

**Comment by mendikant** [comment]
Danke!!!
