### ISSUE TITLE
Daten kommen von DP1500 Pro nicht an 

### ISSUE THREAD

**Issue by Tubbi22** [SBorg2014/WLAN-Wetterstation#52]
Hallo, ich habe doe WLAN Wetterstation soweit installiert und im IOBroker die Datenpunkte angelegt nach Anleitung - sieht alles gut aus.

Ebenso habe ich mit WS View konfiguriert.

Leider kommen aber keine Daten an
-------
Connection to 192.168.1.201 8087 port [tcp/*] succeeded!

Warte maximal 66 Sekunden auf Datenpaket der Wetterstation...

Listening on [0.0.0.0] (family 2, port 1080)
-----------
Da kommt nichts.
Wo könnte ich noch suchen?

**Comment by SBorg2014** [comment]
Hi, an der Stelle ist es noch recht rudimentär. Die Verbindung zum ioB steht, die zum Gateway [ab jetzt GW] offenbar nicht.

Stell es dir wie einen Telefonanruf vor. Es gibt einen reinen Zuhörer (=der Rechner auf dem das Skript läuft [ggf. ist dies derselbe auf dem der ioB läuft, muss aber nicht]) und einen reinen Sprecher (=GW).
Dein Rechner hört jetzt zwar zu, der Sprecher spricht aber nix, auch nicht in der falschen Sprache.

Es liegt offenbar an deinem GW. "Spricht" nix = GW kaputt (klammern wir mal aus)
Wahrscheinlicher hat er die falsche Nummer/Durchwahl und "ruft" einfach jemanden ganz anderes an ;)

Er braucht also die richtige Durchwahl (=Port) damit genau das gewünschte Telefon klingelt, und natürlich erst mal die richtige Telefonnummer (=IP-Adresse).

Hast du in der WS-View[+] App also wirklich Port 1080 (sehe ich oben) und die korrekte IP-Adresse des Rechners eingetragen auf dem das Skript läuft (kann zwar derselbe wie der ioB-Rechner sein, muss es aber nicht. Es **muss** die IP des Rechners sein auf dem das Skript läuft!)?

**Comment by Tubbi22** [comment]
das ist es ja, es sieht alles passend aus:

Debug VAR:
 Installationsverzeichnis: /home/pi/wetterstation
 IPP: 192.168.1.201:8087        WS_PORT: 1080           WS_POLL: 30            PRE_DP: javascript.0.Wetterstation
 WEB: HTTP              WS_PROT: Ecowitt

![grafik](https://user-images.githubusercontent.com/122726747/212548376-e7981822-e96f-4672-b7b3-6a25725df68a.png)

**Comment by SBorg2014** [comment]
Sieht nicht nur passend aus, solange das Skript nun auch auf dem selben Rechner (IP...201) wie der ioB läuft.
Überträgst du Daten an Ecowitt oder Wunderground? --> dann wäre auch das Gateway operabel (+ zumindest nicht defekt)
Kannst du es vom 201er-Rechner aus anpingen?

**Comment by Tubbi22** [comment]
Die Übertragung am Wunderground läuft - ping klappt nicht

Am 16.01.2023 um 10:12 schrieb SBorg2014:

**Comment by SBorg2014** [comment]
Wenn du ihn per ping nicht erreichst, geht auch die andere Richtung nicht, er kann also keine Daten an die ...201 schicken. Da musst du dein Netzwerk/Einrichtung/DP1500-Gateway-Einstellungen mal prüfen.
Fritz!Box als Router? --> dann sollte da das Gateway bei den Netzwerkgeräten erscheinen

**Comment by Tubbi22** [comment]
Sorry, dass ich nochmals störe -  die Kommunikation passt nun (hatte GW ins Gast Wlan eingebunden und dann klappt es nicht), Nun kommen Daten an, die sehen aber strukturell anders aus (siehe Block "Daten von Wetterstation),:

 WLAN-Wetterstation V2.20.0 - (c)2019-2022 by SBorg
 Config-Version: V2.20.0
 Sub-Version   : V2.20.0

 'bc' installiert: [✓]
 'jq' installiert: [✓]

 'dc' installiert: [✓]

 'nc' in der Openbsd-Variante installiert:  [✓]
 'netcat' in Openbsd-Variante aktiv, alles korrekt [✓]


Connection to 192.168.1.201 8087 port [tcp/*] succeeded!


Messwerteblock:


Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

Temperatur Innen        :  °C
Temperatur Aussen       :  °C
Taupunkt                :  °C
Gefühlte Temperatur     :  °C
Luftfeuchte Innen       :  %
Luftfeuchte Aussen      :  %
Windgeschwindigkeit     :  km/h
Windgeschwindigkeit 10min       :  km/h
Windböengeschwindigkeit :  km/h
max. Windböe            :  km/h
Windrichtung            :  °
Windrichtung            :
Windrichtung 10min      :  °
Luftdruck absolut       :  hPa
Luftdruck relativ       :  hPa
Regenrate               :  mm/h
Regenstatus             :
Regen seit Regenbeginn  :  mm
Regen Stunde            :  mm
Regen Tag               :  mm
Regen Woche             :  mm
Regen Monat             :  mm
Regen Jahr              :  mm
Regen Gesamt            :  mm
Sonnenstrahlung         :  W/m²
UV-Index                :
Zeitstempel             :
Firmware                :
Batteriestand:          :
Gateway-Modell          :

Zusatzsensoren:



Datenstring für ioBroker:



DATA von Wetterstation:
PASSKEY=xxxxxx&stationtype=GW1100A_V2.2.1&runtime=295189&dateutc=2023-01-17+19:56:40&tempinf=65.12&humidityin=54&baromrelin=28.990&baromabsin=28.990&tf_ch1=29.  12&tf_batt1=1.46&freq=868M&model=GW1100A&interval=30


Debug VAR:
 Installationsverzeichnis: /home/pi/wetterstation
 IPP: 192.168.1.201:8087        WS_PORT: 1080           WS_POLL: 30             PRE_DP: javascript.0.Wetterstation
 WEB: HTTP              WS_PROT: Ecowitt

Zusatzsensoren:
 DP10/35/40/50/60/70/100/200/250/300: 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
 WH31: 0 || WS90: 0

Script-Version: V2.20.0 Config-Version: V2.20.0 Sub-Version: V2.20.0

Kommunikationsfehler!

**Comment by SBorg2014** [comment]
Du störst nicht und schön das nun die Daten eintrudeln. Das andere Aussehen der Daten (und der Fehler) rühren einfach davon, dass das Projekt nicht umsonst "WLAN-Wetterstation" heißt. Ein DP35-Sensor ist nun mal keine Wetterstation ;)
Da fehlen die Daten für Sonne, Wind, Regen.... die vom Skript aber später vorausgesetzt werden. Ohne die würde es massig Fehler hageln, deswegen wird beim Fehlen dieser Daten vorher abgebrochen.
Du bräuchtest also ev. noch einen Wettermast oder einen WS90 "Wittboy", oder, falls es nur beim DP35 bleiben soll zB. einen NodeRED-Flow (lemuba hat im ioBroker-Forum einen zur Verfügung gestellt. Da könnte man dann einfach die nicht benötigten Flows von Regen, Wind etc. löschen).

**Comment by Tubbi22** [comment]
Ok, prima und vielen Dank - wollte zunächst schauen, ob ich die Daten in
den ioBroker bekomme und dann das "richtige" Gerät erwerben.

Vielen Dank für Deine Hilfe.

Am 18.01.2023 um 00:40 schrieb SBorg2014:
