### ISSUE TITLE
Vorjahres-Monat Statistik geht schief

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#54]
Hallo.
Heute nach bei der Statistikauswertung folgende log-Einträge:

<html>
<body>

javascript.0 | 2023-02-01 01:03:00.244 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Regentage" has to be type "number" but received type "object"
-- | -- | -- | --
javascript.0 | 2023-02-01 01:03:00.243 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Tropennaechte" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.242 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Wuestentage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.241 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.sehr_kalte_Tage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.240 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Eistage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.239 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.kalte_Tage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.239 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Frost_Tage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.238 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.heisse_Tage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.236 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Sommertage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.236 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.warme_Tage" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.235 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Regenmenge_Monat" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.234 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Max_Regenmenge" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.233 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Max_Windboe" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.232 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Temperatur_Durchschnitt" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.230 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Hoechstwert" has to be type "number" but received type "object"
javascript.0 | 2023-02-01 01:03:00.229 | info | State value to set for "0_userdata.0.Statistik.Wetter.Vorjahres_Monat.Tiefstwert" has to be type "number" but received type "object"

</body>
</html>

die dazugehörigen Objekte zeigen daher nur Schrott an:
![grafik](https://user-images.githubusercontent.com/84717453/216069739-c58e644a-51ff-47eb-a5bb-4394ea23518c.png)
Benutzte script-Version: v1.3.0

danke
lg Manfred

**Comment by SBorg2014** [comment]
Fixed in V1.3.1
Im Forenthread ([https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/4397](https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/4397)) kommt dann noch ein kleiner Snippet, um die Daten für den Februar zu erhalten.
