### ISSUE TITLE
Adapter WH31

### ISSUE THREAD

**Issue by mendikant** [SBorg2014/WLAN-Wetterstation#56]
Hey, ich bin es leider schon wieder.

Da meine wh90 relativ hoch in der prallen Sonne hängt, habe ich mir einen Wh31 dazu besorgt, der jetzt an einer Nordwand auf 2m Höhe die Temperatur misst. 

Ich habe den WH31 mit dem Javascript neu als Datenpunkt angelegt und die wetterstation.sh angepasst.
Im iobroker hast du für den WH31 nur einen Datenpunkt für die Batterie vorgesehen.Der aber nicht befüllt wird.
Temperatur und Luftfeuchte sind bisher nicht vorgesehen. Das sind in der Ausgabe unten die temp1f und die humidity1

Kannst Du da noch was machen? Cool wäre es, wenn ich in der Config sagen könnte: Nimm bitte die Daten für die Außentemperatur/feuchtigigkeit...  ;-) aber ich käme klar, wenn sie als Datenpunkte existierten.

Herzlichen Dank 
Christian

Das hier ist die Debugausgabe:

Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=19.10&javascript.0.Wetterstation.Aussentemperatur=8.90&javascript.0.Wetterstation.Taupunkt=6.00&javascript.0.Wetterstation.Gefuehlte_Temperatur=8.08&javascript.0.Wetterstation.Innenfeuchtigkeit=44&javascript.0.Wetterstation.Aussenfeuchtigkeit=82&javascript.0.Wetterstation.Wind=6.48&javascript.0.Wetterstation.Wind_max=10.79&javascript.0.Wetterstation.Windrichtung=301&javascript.0.Wetterstation.Druck_absolut=1006.60&javascript.0.Wetterstation.Druck_relativ=1006.60&javascript.0.Wetterstation.Regenrate=0&javascript.0.Wetterstation.Regen_Tag=1.193&javascript.0.Wetterstation.Regen_Woche=2.209&javascript.0.Wetterstation.Regen_Monat=8.305&javascript.0.Wetterstation.Regen_Jahr=8.305&javascript.0.Wetterstation.Sonnenstrahlung=45.54&javascript.0.Wetterstation.UV_Index=0&javascript.0.Wetterstation.Zeitstempel=20.02.2023%2016:54:04&javascript.0.Wetterstation.Info.FW_Version=GW2000A_V2.2.2&javascript.0.Wetterstation.Windboeen_max=19.79&javascript.0.Wetterstation.Info.Wetterstation_Gateway=GW2000A&javascript.0.Wetterstation.WS90.1.aktuelle_Regenrate=0&javascript.0.Wetterstation.WS90.1.aktuelle_Regenmenge=1.193&javascript.0.Wetterstation.WS90.1.stuendliche_Regenmenge=.101&javascript.0.Wetterstation.WS90.1.taegliche_Regenmenge=1.193&javascript.0.Wetterstation.WS90.1.woechentliche_Regenmenge=2.209&javascript.0.Wetterstation.WS90.1.monatliche_Regenmenge=8.305&javascript.0.Wetterstation.WS90.1.jaehrliche_Regenmenge=8.305&javascript.0.Wetterstation.WS90.1.Spannung_GoldCap=5.3&javascript.0.Wetterstation.WS90.1.Firmwareversion=126&javascript.0.Wetterstation.WS90.1.Batterie=2.98&javascript.0.Wetterstation.Regenstatus=kein Regen&javascript.0.Wetterstation.UV_Belastung=keine&javascript.0.Wetterstation.Windrichtung_Text=WNW&javascript.0.Wetterstation.Info.Hitzeindex=

DATA von Wetterstation:
PASSKEY=xxxxxx&stationtype=GW2000A_V2.2.2&runtime=2751318&dateutc=2023-02-20+15:54:04&tempinf=66.38&humidityin=44&baromrelin=29.725&baromabsin=29.725&tempf=48.02&humidity=82&winddir=301&windspeedmph=4.03&windgustmph=6.71&maxdailygust=12.30&solarradiation=45.54&uv=0&rrain_piezo=0.000&erain_piezo=0.047&hrain_piezo=0.004&drain_piezo=0.047&wrain_piezo=0.087&mrain_piezo=0.327&yrain_piezo=0.327&ws90cap_volt=5.3&ws90_ver=126&temp1f=48.56&humidity1=79&batt1=0&wh90batt=2.98&freq=868M&model=GW2000A&interval=30

**Comment by SBorg2014** [comment]
Hallo Christian,
hier gibt es kein "leider" ;-)
Nutzt du kein Influx beim Shell-Skript, und falls doch V2.x? Dann kannst du die neue V3.0.0 ausprobieren und den FT0300-Sensor nutzen, da sollten dann schon die Daten kommen.
