### ISSUE TITLE
Fehler Auswertung Monatserster

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#58]
siehe Log.

<html>
<body>

javascript.0 | 2023-03-01 01:03:00.018 | error | at processTimers (node:internal/timers:502:7)
-- | -- | -- | --
javascript.0 | 2023-03-01 01:03:00.018 | error | at listOnTimeout (node:internal/timers:559:17)
javascript.0 | 2023-03-01 01:03:00.018 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:228:7)
javascript.0 | 2023-03-01 01:03:00.018 | error | at /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Invocation.js:268:28
javascript.0 | 2023-03-01 01:03:00.017 | error | at Job.invoke (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-schedule/lib/Job.js:171:15)
javascript.0 | 2023-03-01 01:03:00.017 | error | at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1595:34)
javascript.0 | 2023-03-01 01:03:00.017 | error | at Object.main (script.js.common.Wetterstatistik.Wetterstatistik_script:148:4)
javascript.0 | 2023-03-01 01:03:00.017 | error | at VorJahr (script.js.common.Wetterstatistik.Wetterstatistik_script:409:17)
javascript.0 | 2023-03-01 01:03:00.016 | error | Error in callback: TypeError: VorJahr.forEach is not a function

</body>
</html>

lg
Manfred

**Comment by SBorg2014** [comment]
fixed in V2.0.2
