### ISSUE TITLE
Statistik nur mehr mit Influx v2?

### ISSUE THREAD

**Issue by mango1402** [SBorg2014/WLAN-Wetterstation#59]
Hallo,
aufgrund meines letzten Issues hab ich auf das letztaktuelle Statistikscript upgedatet.
Und klar, heute kamen die Meldungen dass Influx keine Daten liefert....
Einsersits weil ich weiterhin Influx v1 verwende, andererseits weil ich im Wetterstation-Script die Daten nicht in Influx schreiben lasse......

Auf die Schnelle ins coding geschaut - sehe ich das richtig und funktioniet das Statistik-script ohne Influx nicht mehr?

lg
Manfred

<html>
<body>

javascript.0 | 2023-03-02 01:03:00.036 | warn | TypeError: Reduce of empty array with no initial value at Array.reduce (<anonymous>:null:null) at Object.cb (script.js.common.Wetterstatistik.Wetterstatistik_script:187:43) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5291:71) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (node:internal/timers:466:21)
-- | -- | -- | --
javascript.0 | 2023-03-02 01:03:00.034 | warn | States system pmessage io.messagebox.system.adapter.javascript.0 {"command":"query","message":{"result":[],"error":"Invalid call"},"from":"system.adapter.influxdb.0","callback":{"message":"from(bucket: \"Wetter\") \|> range(start: 1677625200, stop: 1677711599) \|> filter(fn: (r) => r._measurement == \"0_userdata.0.Wetterstation.Aussentemperatur\") \|> filter(fn: (r) => r._field == \"value\"); from(bucket: \"Wetter\") \|> range(start: 1677625200, stop: 1677711599) \|> filter(fn: (r) => r._measurement == \"0_userdata.0.Wetterstation.Wind_max\") \|> filter(fn: (r) => r._field == \"value\"); from(bucket: \"Wetter\") \|> range(start: 1677625272, stop: 1677711599) \|> filter(fn: (r) => r._measurement == \"0_userdata.0.Wetterstation.Regen_Tag\") \|> filter(fn: (r) => r._field == \"value\")","id":12,"ack":true,"time":1677715380015},"_id":63912658} Reduce of empty array with no initial value
javascript.0 | 2023-03-02 01:03:00.033 | error | script.js.common.Wetterstatistik.Wetterstatistik_script: Fehler beim Lesen der InfluxDB: Invalid call
influxdb.0 | 2023-03-02 01:03:00.019 | error | query: Error: error parsing query: found FROM, expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1
javascript.0 | 2023-03-02 01:03:00.016 | info | script.js.common.Wetterstatistik.Wetterstatistik_script: Auswertung durchgeführt...

</body>
</html>

**Comment by SBorg2014** [comment]
Ich sag mal jein.
Die Statistik hat noch nie ohne Influx funktioniert. Von irgendwoher muss ich zB. die Temperaturen des Tages herbekommen. Das geht nur via Datenbank, denn die Station liefert nur den aktuellen Wert.
Ich schreibe, weder bei der Statistik noch beim Shell-Skript, etwas in die InfluxDB hinein. Dies gilt für bisher alle Versionen. Es wird nur gelesen.
V3 Shell-Skript und V2 Statistik sind nur noch InfluxDB V2.x kompatibel. Dazu gab es eine Diskussion im Forum die einstimmig für InfluxDB V2 war. Du kannst aber bspw. beides parallel fahren (mache ich derzeit auch noch), oder wenn du bei InfluxDB V2.x das "Bucket" (so heißt nun die ehemalige Database) auf InfluxQL belässt und nicht auf Flux umstellst, ändert sich auch sonst erst mal nichts (zB. Grafana-Dashboards). Denn V2 ist abwärtskompatibel zu V1 ;)

**Comment by mango1402** [comment]
Danke für die Info.
das heißt für alle mit alten Raspi's ohne 64-Bit System kann Dein Script nicht mehr verwendet werden.
Oder auch für all jene, die nicht auf V2 updaten können oder wollen - wie ich ;)
Ich hab lange herumgespielt, Update selbst ist nicht das Problem. Aber dann wird's spannend: eCharts und Flot legen Influx V2 lahm, die CPU-Load geht auf >100% und es kommen keine bzw. nur sehr schleppend Daten am Graphen an......
Also Du färhst mit Influx V1 und Influx V2 parallell installiert? Geht das überhaupt auf einer Maschine?

**Comment by SBorg2014** [comment]
Dem Shell-Skript ist es egal ob du Influx nutzt oder nicht, dir fehlen dann nur die mit (4) gekennzeichneten Werte wie bspw. Min/Max Temperatur der letzten 24h / Heute / vor einem Jahr.
Aber aktuell gibt es als einzigen Unterschied zwischen den Versionen von Shell- und Statistik-Skript nur die Influx-Funktionalität. Die neue(n) Version(en) macht nichts besser, nutzt halt nur InfluxDB V2.
...und ganz ehrlich, wer SmartHome, ioB etc. einsetzt und dann auch schon bei InfluxDB gelandet ist, der ist über den Einstieg schon hinaus und wird wohl ernsthaft keinen PI mehr benutzen. ...oder er nimmt die alten Versionen.
Ich wollte kein Risiko eingehen, da in meiner DB ca. 4 Jahre an Daten stecken die ich gerne behalten möchte. Deswegen habe ich die InfluxDB V2.61 aktuell in einem Docker auf meiner Synology laufen und ziehe da Stück für Stück um.

**Comment by mango1402** [comment]
Was hältst Du davon?
[wetterstation-statistik_v202a.js.txt](https://github.com/SBorg2014/WLAN-Wetterstation/files/10872773/wetterstation-statistik_v202a.js.txt)

**Comment by SBorg2014** [comment]
Das würde funktionieren, allerdings ist dies keine Frage des "wie", sondern des "ob". Und zum "ob" gibt es ein nein. Nach knapp 1.5 Jahren ist der Wechsel nicht mal sehr früh erfolgt und solange erhielt auch V1 schon keine Updates mehr, also nur noch toter Ballast (und **kein** Einziger User sprach sich auch dafür aus). Man kann, wenn man denn unbedingt V1 behalten möchte, einfach die alte V1.3.x weiter nutzen, die ist identisch mit der aktuellen Version.
Spätestens mit neuen Abfragen/Umstrukturierung zur besseren Performance ist dann eh mit InfluxDB V1 Schluss, denn das kann InfluxQL einfach nicht, da braucht es schon Flux.

**Comment by mango1402** [comment]
Ja schade....
