### ISSUE TITLE
Frage zu Umzug auf InfluxDB V2.x

### ISSUE THREAD

**Issue by Domi920** [SBorg2014/WLAN-Wetterstation#60]
Hallo,
würde gerne das neue Update anwenden.
Für die Statistik benutze ich bereits InfluxDB V1.

Wie muss ich neben deiner Updateanleitung
(https://github.com/SBorg2014/WLAN-Wetterstation/wiki/Update-auf-eine-neue-Version)
weiter vorgehen?

Gibt es eine Möglichkeit die bestehenden InfluxDB Daten zu sichern?
Kann man die Daten sehen, egal ob InfluxDB V1 oder V2.x?

Eine frage noch nebenbei:
Würde gerne noch weitere Daten von anderen Geräten in einer InfluxDB V2.x speichern.
Macht es deiner Meinung nach Sinn, 2 verschiedene InfluxDB Instanzen in IOBroker zu haben?
Falls ja, muss man auf dem Raspberry Pi 4 B eine weitere Influx Datenbank parallel zur anderen installieren, oder wie läuft das?
Würde es theoretisch auch funktionieren die gleiche Instanz zu nutzen? (Weil einfach nur mehr Daten mitgeloggt werden)

Am Ende möchte ich alle Daten in Grafana anzeigen lassen.

Vielen Dank für Deine Infos & Deine Hilfe!

Gruß Dominik

**Comment by SBorg2014** [comment]
Hi, das wäre im Forum besser aufgehoben, da ich keinen "Einzel-Support" leisten kann und GitHub da auch nicht gerade Anwenderfreundlich ist ;)
InfluxDB lässt sich per CLI sichern, oder man nimmt im ioB einfach den BackitUp-Adapter.
In V2 gibt es eine Web-GUI über die sich die Daten anzeigen lassen (sogar als Graph).

Da pro Bucket (=Datenbank) nur eine Retention (Aufbewahrungsfrist) möglich ist, muss man hier mit mehren Instanzen arbeiten (=kostet richtig RAM), oder man entscheidet sich alles zB. immer nach 30 Tagen löschen zu lassen.
Flexibler ist ein Bucket mit einer Retention von bspw. 90 Tagen und alles was man darüber hinaus behalten möchte per Influx-Tasks in ein separates Bucket zu shiften (ganz ohne Influx-Instanz + dann mit einer Retention von "never").

**Comment by Domi920** [comment]
Hallo,
vielen Dank für deine Antwort, auch wenn es kein Thema für ein Issue gewesen ist.

Habe die letzten Tage genutzt, um meinen Raspberry-Pi-4-B-8-GB von SD auf SSD Festplatte umgerüstet.
Außerdem habe ich nun das 64 Bit Betriebssystem installiert.

Ich habe mich dazu entschieden, die "alten" Daten von InfluxDB V1.x zu verwerfen und bin zur neuen InfluxDB V2.x gewechselt.

Mit der Neuaufsetzung meines Raspberry Pi habe ich auch Deine Anleitung zur Installation befolgt.
Allerdings muss ich feststellen, dass ich keine V3 von Deiner Software bekomme.
Auch nicht, wenn ich die Update Prozedur im Wiki ausführe.

Wie kann ich nun auf die V3 wechseln?
Habe aktuell auch noch keinen Datenpunkt mit InfluxDB geloggt und brauche mir keine Gedanken um die Migration machen.


Vielen Dank für Deine Hilfe!
Werde das Issue nach deiner Antwort gleich schließen.

Gruß Dominik

**Comment by SBorg2014** [comment]
Hi, keine Angst, ein Issue ist von meiner Seite aus nichts schlechtes/negatives.
Die Update-/Wiki-Anleitung bezieht sich nur auf Release-Versionen. Die V3 ist aktuell noch im Beta-Stadium (läuft aber bisher problemlos) und lässt sich nur per Hand installieren: https://forum.iobroker.net/post/948445

**Comment by Domi920** [comment]
> Hi, keine Angst, ein Issue ist von meiner Seite aus nichts schlechtes/negatives. Die Update-/Wiki-Anleitung bezieht sich nur auf Release-Versionen. Die V3 ist aktuell noch im Beta-Stadium (läuft aber bisher problemlos) und lässt sich nur per Hand installieren: https://forum.iobroker.net/post/948445

Vielen Dank für deine Info!
Hat alles wunderbar geklappt :-)

Gruß Dominik
