### ISSUE TITLE
Ergänzung für Wiki zur Installation unter Proxmox-Container

### ISSUE THREAD

**Issue by Gelbwichtel** [SBorg2014/WLAN-Wetterstation#63]
Hi, erst mal Lob für dein tolles Projekt. Nachdem ich mich zuerst an an einer Sainlogic **FT0300** versucht habe (kläglich gescheitert, weil die Screenshots, die das Umbiegen der DNS Adressen kaum leserlich skalierbar sind und auch das PiHole Setup dazu geführt hat, dass vielzuviel weggeblockt wurde) bin ich auf eine **WS3500** umgeswitcht. Zum Testen wollte ich mein Produktivsystem nicht belasten und hab es erst einmal in einer **Proxmox** Umgebung versucht. Aber weder die Installation unter **Debian**, noch unter **Ubuntu** lief sauber durch.

Hier mal die wesentlichen Punkte, die vor dem ws_updater.sh Skript noch auszuführen sind:

- Unter Debian muss das "**sudo**" Paket nachinstalliert werden: **`apt-get install sudo`**
- da auf den Containerinstallationen zunächst nur mit "**root**" gearbeitet werden kann, muss ein neuer User z.B. "**wetter**" eingerichtet werden. Also **`adduser wetter`** aufrufen und Passwort eintragen. Bei allen anderen Abfragen kann der leere Default mit Enter übernommen werden
- der User "**wetter**" muss der "**sudo**" Gruppe zugeordnet werden: **`usermod -aG sudo wetter`**
- danach mit User "**wetter**" einloggen und mit deinen Installationschritten fortfahren

Hoffe ich habe nichts vergessen
LG Gelbwichtel

**Comment by SBorg2014** [comment]
Hi, leider die liebe Zeit. So ein Projekt ist nicht gerade mal in ein paar Stunden erledigt. Da war ich schon froh, dass sich wenigstens einer erbarmt hat mal den PiHole-Part zu dokumentieren. Man kann bei PiHole auch das blocken gänzlich lassen und nur das "verbiegen" nutzen. Oder es müsste mal einer per dnsmasq arbeiten + dokumentieren, dann geht es ohne weitere Software. Aber die liebe Zeit...
Ich habe jetzt schon einen Tag hin und her überlegt, ob das in die WiKi soll/muss oder nicht. Im Grunde bin ich zwar immer dafür jeden zu unterstützen wo es nur geht, andererseits ist die Doku eh schon zu lang und die wenigsten lesen dort nach.
Irgendwo muss ich dann auch eine Grenze ziehen und kann bspw. nicht auch noch erklären wie man Linux installiert. In "deinem" Fall ist die Grenze eigentlich auch schon überschritten, denn "sudo" und ein Userkonto (es gibt __keinen__ Grund als *root* zu arbeiten) gehört zur Grundinstallation eines Systems und ist nicht nur spezifisch für das Skript nötig. Die WLAN-Skript spezifischen Befehle installiere ich bspw. nach falls sie auf dem System fehlen.
Hier mag auch mal die Installation eines Adapters im ioB herhalten. Da ist die Voraussetzung ein installiertes BS und der ioB. Zeige mir einen Adapter der in der Hilfe erklärt wie der ioB und das BS installiert wird ^^
...aber was schadet es schon wenn es am Ende eh kaum einer ließt...

**Comment by SBorg2014** [comment]
Done
