### ISSUE TITLE
Weiterer Sensor

### ISSUE THREAD

**Issue by mendikant** [SBorg2014/WLAN-Wetterstation#64]
Hi,

ich habe mir für die Überwachung von Wassertemperatur einen WN34 bestellt. Kann ich den einfach als zweiten wh31 deklarieren, oder ist das aufwendiger?

Vielen Dank und viele Grüße

**Comment by SBorg2014** [comment]
Hi, einfach in der conf und im DP-JS-Anlegeskript entsprechend die Sensoranzahl um "eins" erhöhen: https://github.com/SBorg2014/WLAN-Wetterstation/wiki/Neue-Sensoren-nachtr%C3%A4glich-hinzuf%C3%BCgen

**Comment by mendikant** [comment]
Würde ich tun, wenn der Sensor WN34 in der Conf aufgelistet wäre. Kann ich den einfach reinschreiben oder wie gesagt einen beliebigen anderen erhöhen?


Werde morgen oder Sonntag aber mal testen und  evtl Protokolldaten hochladen

**Comment by SBorg2014** [comment]
Ist er aber, steht in der *wetterstation.js* und in der READ.ME bei *Zusatzsensoren* ;)
`let DP35 = 0;    // Anzahl der DP35/WN34 Sensoren  (max. 8 Stück)`

Ist leider blöd, da Froggit/Ecowitt unterschiedliche Bezeichnungen für die gleichen Sensoren haben.

**Comment by mendikant** [comment]
Oh mann, da hätte ich drauf kommen können. Danke herzlich. Temperatur ist im Iorboker angekommen. 

VG
