### ISSUE TITLE
Inbetriebnahme auf  Proxmox und VM

### ISSUE THREAD

**Issue by hakelgg** [SBorg2014/WLAN-Wetterstation#66]
Hallo
bin dabei mit dem Iobroker vom Pi auf Intel NUC und Proxmox umzuziehen.
Zustand: Iobroker läuft, Zigbee läuft, RTL-433 läuft, WLAN-Wetterstation installiert.
Problem:  Projekt WLAN-Wetterstation läuft nur wenige Sekunden.
./wetterstation.sh --debug  läuft erfolgreich durch.
 systemctl status wetterstation  nach wenigen Sekunden gestartet meldet Fehler.
Noch eine Idee?
[Debug.txt](https://github.com/SBorg2014/WLAN-Wetterstation/files/12123432/Debug.txt)
[Status.txt](https://github.com/SBorg2014/WLAN-Wetterstation/files/12123433/Status.txt)

**Comment by SBorg2014** [comment]
Hi,
die ersten "...line 725: printf..." Fehler verschwinden von alleine wenn es denn mal läuft.
Die 
``` 
"error": "datapoint \"0_userdata.0.Wetterstation.BR7009999.1.Temperatur\" not found"
```
und folgende: da sind die Datenpunkte im ioB nicht/nicht korrekt angelegt. Hast du in der "wetterstation.js" die korrekte/richtige Anzahl der Sensoren eingetragen gehabt? (kannst du jederzeit einfach nochmal laufen lassen)

...und der Hauptfehler: kann es sein, dass du in der `wetterstation.conf` eventuell "debug=true" stehen hast? Dann bricht er nämlich genau nach einem Durchlauf ab (ist so gewollt, denn andernfalls müllt er nur das System-Log voll).

**Comment by hakelgg** [comment]
Läuft
das Problem befindet sich meistens vor dem Bildschirm.

Danke.

Bei Installationsanleitung:
**`"neuen User z.B. "wetter" anlegen:  useradd -m wetter aufrufen und Passwort eintragen. Bei allen anderen Abfragen kann der leere Default mit Enter übernommen werden."`**
bitte "`useradd -m wetter`"  in "`adduser wetter`" ändern.
Bei Verwendung `useradd `wird kein Passwort angelegt. 

`adduser`
- erfolgt Abfrage neues  `Passwort`
-  legt Stammverzeichnis "`wetter`" auch an 



Vielen Dank und angenehmes Wochenende
