### ISSUE TITLE
Nach Neuinstallation fährt der Dienst nicht hoch Kommunikationsfehler!

### ISSUE THREAD

**Issue by nhet** [SBorg2014/WLAN-Wetterstation#67]
Ich habe die Bresser 7in1 HD Station neu.
https://www.bresser.de/P7003500

Nach einer Neuinstallation fährt der Dienst nicht hoch. 
./wetterstation.sh --debug sagt dazu folgende Meldungen:

`WLAN-Wetterstation V3.1.1 - (c)2019-2023 by SBorg
 Config-Version: V3.0.0
 Sub-Version   : V3.1.1

 'bc' installiert: [✓]
 'jq' installiert: [✓] 

 'dc' installiert: [✓] 

 'nc' in der Openbsd-Variante installiert:  [✓]
 'netcat' in Openbsd-Variante aktiv, alles korrekt [✓]

Connection to 192.168.0.152 8087 port [tcp/*] succeeded!

Messwerteblock: 

Nicht alle Werte werden unterstützt (abhängig vom Modell der Wetterstation und dem verwendeten Protokoll)!

 Temperatur Innen		:  °C
 Temperatur Aussen		:  °C
 Taupunkt			:  °C
 Gefühlte Temperatur		:  °C
 Luftfeuchte Innen		:  %
 Luftfeuchte Aussen		:  %
 Windgeschwindigkeit		:  km/h
 Windgeschwindigkeit 10min	:  km/h
 Windböengeschwindigkeit	:  km/h
 Windböe max.			:  km/h
 Windrichtung			:  °
 Windrichtung			: 
 Windrichtung 10min		:  °
 Luftdruck absolut		:  hPa
 Luftdruck relativ		:  hPa
 Regenrate			:  mm/h
 Regenstatus			: 
 Regen seit Regenbeginn		:  mm
 Regen Stunde			:  mm
 Regen Tag			:  mm
 Regen Woche			:  mm
 Regen Monat			:  mm
 Regen Jahr			:  mm
 Regen Gesamt			:  mm
 Sonnenstrahlung		:  W/m²
 UV-Index			: 
 Zeitstempel			: 
 Firmware			: 
 Batteriestand:			: 
 Gateway-Modell			: 

Zusatzsensoren:

Datenstring für ioBroker:

DATA von Wetterstation:

Debug VAR:
 Installationsverzeichnis: /opt/ioBrokerHelper/wetter
 IPP: 192.168.0.152:8087	WS_PORT: 80		WS_POLL: 30		PRE_DP: 0_userdata.0.Wetterstation
 WEB: HTTP		WS_PROT: DNS

Zusatzsensoren:
 DP10/35/40/50/60/70/100/200/250/300: 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 
 WH31: 0 || WS90: 0
 Bresser: 7009999 [0]

Script-Version: V3.1.1	Config-Version: V3.0.0	Sub-Version: V3.1.1

Kommunikationsfehler!
`

Was hab ich falsch gemacht?

**Comment by SBorg2014** [comment]
Hi, dein Problem ist, dass das Display keine Daten schickt bzw. der Rechner mit dem Skript keine Daten empfängt.
IMO muss hier aber gar nicht mittels "DNS-Verbiegung" gearbeitet werden?
> ...ProWeatherLive, Weather Underground, Weathercloud sowie 1 zusätzliche benutzerdefinierte Plattform

Damit müsste sie eigentlich direkt ("1 zusätzliche  benutzerdefinierte Plattform") ansprechbar sein. Trag da mal die Daten (wie in der WiKi beschrieben) deines Systems ein und stell dann mal das Protokoll auf "2" oder "1" in der *wetterstation.conf* um, je nachdem ob die Station da Wunderground oder Ecowitt (ich glaube das kann sie nicht) unterstützt.

**Comment by nhet** [comment]
Beste dank für die schnelle Antwort. Ich werde das mal testen. Was ich schon sagen kann ist, dass ich die Werte 2 und 3 für das Protokoll schon eingestellt hatte. Bei beiden kam halt dieser Fehler und zwar direkt und ohne Wartezeit beim Programmstart.

**Comment by nhet** [comment]
Nach einer kurzen Pause habe ich es heute noch einmal ausprobiert. 
Meine Wetterstation muss doch über DNS angesprochen werden. Zumindest klappt das jetzt so.
Das eigentliche Problem, warum keine Werte kamen, waren die folgenden zwei:

1. nc läuft auf Port 80 und das darf nur root. Lösung: sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/nc.openbsd
2. WS_ID war nicht korrekt gesetzt. Lösung: Anpassen. Für meinen Fall war das die ID aus awekas

Jetzt läuft es. 
Nur so am Rand sehe ich im Log noch systax errors und das nicht zu wenige. Vielleicht kann man da noch was machen? @SBorg2014 ?

(standard_in) 1: syntax error
(standard_in) 12: syntax error
(standard_in) 1: syntax error


Ansonsten kann der Vorgang gerne geschloßen werden.

**Comment by SBorg2014** [comment]
Hi,
 1. stand nur in der "normalen" Anleitung, nicht im DNS-WiKi --> habe ich ergämzt, danke
 2. wahrscheinlich hast du als Übertragungsweg nicht Wunderground sondern AWEKAS ausgewählt. Bis auf die URL und eben die Zugangsdaten sind aber beide identisch
  
Die Fehler sollten mittlerweile weg sein. Wenn man den ungünstigsten Augenblick (wenn turnusmäßig intern Routinen laufen) für den Erstart erwischt, dann liegen 1-2 Werte nicht vor und er wirft zu Recht den/die Fehler. Spätestens nach der 1. vollen Viertelstunde hat er dann alles und die Berechnung klappt dann auch.
