### ISSUE TITLE
Bresser 5-1 / Gefühlte Temperatur stimmt nicht

### ISSUE THREAD

**Issue by GitHubLawe** [SBorg2014/WLAN-Wetterstation#68]
Hallo,
es scheint so, als stimmt einer der Werte (Aussentemperatur oder Gefühlte Aussentemperatur) nicht.

An der Station selbst sind es unterschiedliche Werte - im ioBroker immer geich:
![image](https://github.com/SBorg2014/WLAN-Wetterstation/assets/100830399/c77ff755-b39a-4bbd-999f-68598eca5c5e)

**Comment by SBorg2014** [comment]
Hi, der sog. Windchill ist ein "Auskühlparameter" (sry, bin kein Meteorologe) der beschreibt wie schnell man Kälte dann wie empfindet. Per Definition gilt das erst ab Temperaturen unter 10°C (ich nehme hier 11°C) und wird noch von der Windgeschwindigkeit beeinflusst. Darüber "fühlt" sich dann bspw. 20°C auch wie 20°C an. Deswegen ist bei >11°C *Aussentemperatur* gleich *Windchill*.
Bei Google steht es unter "windchill" besser erklärt ^^

Die Station sollte es dann eigentlich genauso handeln oder gar nichts anzeigen?

**Comment by GitHubLawe** [comment]
Die Station zeigt tatsächlich andere Werte an. Gerade 34 Grad gefühlt wie 38 (Hohe Luftfeuchtigkeit / Gewittee im anmarsch) gestern auch öfters 30 gefühlt wie 26 weil sehr windig

**Comment by SBorg2014** [comment]
Stoppe mal den Service `[sudo] systemctl stop wetterstation` und führe dann im Installationsverzeichnis stehend ein `./wetterstation.sh --data` aus. Ist in dem Datenstring der *windchillf=* enthalten ? Wenn der übertragen wird sollte er den eigentlich in den ioB übertragen, so der Plan... 😏
Service wieder starten nicht vergessen `systemctl start wetterstation`

**Comment by GitHubLawe** [comment]
Danke Dir - aktuell kein windchill(f) im string zu sehen - aktuell zeigt die Station aber auch für Temp / gefühlte Temp das gleiche an auf dem Display. Ich prüfe den String noch mal, wenn unterschiedliches angezeigt wird.

**Comment by SBorg2014** [comment]
Ok, Bresser ist etwas "spezieller" als Andere, dass die aber den String selektiv ändern ist mir nicht bekannt. Normalerweise wird er dann auf "nix" gesetzt: *abc=*, dass sie dann aber den Teil des Strings nicht übertragen kann ich mir ehrlich gesagt nicht vorstellen.
Ich würde eher darauf tippen, dass dieser nie gesendet wird und nur intern für das Display genutzt wird.
Falls kein "windchillf" vom Display kommt, greift immer meine eigene Berechnung (meine Station schickt bspw. auch keinen windchill) nach oben genanntem Muster,
