### ISSUE TITLE
JS-Script "Wetterstatistik"Trockenperiode wird mit 365 Tagen befüllt

### ISSUE THREAD

**Issue by ch33f** [SBorg2014/WLAN-Wetterstation#69]
Bei mir wird sehr oft die Trockenperiode in der Jahresstatistik auf 365 Tage gesetzt, hier ein Verbesserungsvorschlag:

    // Trockenperiode
        // Aktuelles Datum erhalten
        let currentDate = new Date();
        let letzterRegenStr = getState(WET_DP + '.Info.Letzter_Regen').val;
        let letzterRegenDatum = null;

        // Überprüfen, ob das Format dem Muster "TT.MM.JJJJ SS:MM" entspricht
        if (letzterRegenStr.match(/\d{2}\.\d{2}.\d{4} \d{2}:\d{2}/)) {
            letzterRegenDatum = new Date(letzterRegenStr.replace(/(\d{2})\.(\d{2})\.(\d{4}) (\d{2}):(\d{2})/, '$3-$2-$1T$4:$5'));
            BerechnungTrockenperiode();
        }

        // Überprüfen, ob der Wert genau aus 10 Ziffern besteht (Unix-Zeitstempelformat)
        else if (letzterRegenStr.match(/^\d{10}$/)) {
            letzterRegenDatum = new Date(parseInt(letzterRegenStr) * 1000);
            BerechnungTrockenperiode();
        }

        // Überprüfen, ob der Wert das Wort "Tag" enthält
        else if (letzterRegenStr.match(/Tag/g)) {
            Trockenperiode_akt = parseInt(letzterRegenStr.replace(/[^0-9\.]/g, ''), 10);
            BerechnungTrockenperiode();
        }

        function BerechnungTrockenperiode() {
            if (letzterRegenDatum !== null) {
                let Trockenperiode_akt = dayOfYear(currentDate) - dayOfYear(letzterRegenDatum);
                if (Trockenperiode_akt < 0) {
                    let daysInLastYear = dayOfYear(new Date(currentDate.getFullYear() - 1, 11, 31));
                    Trockenperiode_akt += daysInLastYear;
                }
                let Trockenperiode_alt = getState(PRE_DP + '.Jahreswerte.Trockenperiode').val;
                if (Trockenperiode_akt >= Trockenperiode_alt) {
                    setState(PRE_DP + '.Jahreswerte.Trockenperiode', Trockenperiode_akt, true);
                }
            }
}

**Comment by SBorg2014** [comment]
Hi, danke, sieht so schon mal gut aus und teste ich die Tage.
Allerdings stellt sich dann die Frage: behebt es nur das Symptom oder die Ursache? Ich denke eher Ersteres, sonst hätten sich bestimmt schon mehr gemeldet bzw. hatte ich es in mittlerweile fast 4 Jahren noch nie. Sieht mir fast danach aus als würde er gelegentlich einen Wert nicht schnell genug lesen können und sollte da besser asynchron gelesen werden.
