### ISSUE TITLE
Einige Daten werden ab 19 Uhr nicht mehr aktualisiert - iobroker

### ISSUE THREAD

**Issue by fred0815** [SBorg2014/WLAN-Wetterstation#7]
Hallo,

leider werden einige Daten ab 19 Uhr im Info Channel nicht mehr aktualisiert (schon vor dem Update). Ich hoffe, es ist im Screenshot zu erkennen. Zudem ich auf die Version 1.53 von easyweather upgedated habe und es steht immer noch die 1.50 dort... restart der wetterstation.sh habe ich durchgeführt.
![image](https://user-images.githubusercontent.com/6215447/89564837-e83a2f80-d81d-11ea-8b55-4aed1129425d.png)

Es hat den Anschein, als ob einige Berechnungen nicht mehr durchgeführt werden. Sonnenscheindauer_Tag bleibt jeden Tag bei 40647 stehen... komisch..

Die Daten empfängt das Skript auf jeden fall...

Connection to 192.168.178.97 8087 port [tcp/*] succeeded!
Listening on [0.0.0.0] (family 2, port 1080)
Connection from ESP-E39300.fritz.box 16868 received!
[
  {
    "id": "javascript.0.Wetterstation.Innentemperatur",
    "val": 37.5
  },
  {
    "id": "javascript.0.Wetterstation.Aussentemperatur",
    "val": 29
  },
  {
    "id": "javascript.0.Wetterstation.Taupunkt",
    "val": 10.22
  },
  {
    "id": "javascript.0.Wetterstation.Chillfaktor",
    "val": 29
  },
  {
    "id": "javascript.0.Wetterstation.Innenfeuchtigkeit",
    "val": 20
  },
  {
    "id": "javascript.0.Wetterstation.Aussenfeuchtigkeit",
    "val": 31
  },
  {
    "id": "javascript.0.Wetterstation.Wind",
    "val": 1.77
  },
  {
    "id": "javascript.0.Wetterstation.Wind_max",
    "val": 1.77
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung",
    "val": 261
  },
  {
    "id": "javascript.0.Wetterstation.Windrichtung_Text",
    "val": "W\n"
  },
  {
    "id": "javascript.0.Wetterstation.Druck_absolut",
    "val": 984.42
  },
  {
    "id": "javascript.0.Wetterstation.Druck_relativ",
    "val": 1008.94
  },
  {
    "id": "javascript.0.Wetterstation.Regenrate",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Tag",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Woche",
    "val": 2.3
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Monat",
    "val": 2.3
  },
  {
    "id": "javascript.0.Wetterstation.Regen_Jahr",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.Sonnenstrahlung",
    "val": 45.51
  },
  {
    "id": "javascript.0.Wetterstation.UV_Index",
    "val": 0
  },
  {
    "id": "javascript.0.Wetterstation.Regenstatus",
    "val": "kein Regen"
  },
  {
    "id": "javascript.0.Wetterstation.UV_Belastung",
    "val": "keine"
  },
  {
    "id": "javascript.0.Wetterstation.Zeitstempel",
    "val": "06.08.2020 19:54:26"
  }
]

Messwerteblock: 99.5 84.2 50.4 84.2 20 31 1.1 1.1 261 29.070 29.794 0.000 0.000 0.091 0.091 0 45.51 0 2020-08-06%2017:54:26 EasyWeatherV1.5.2

Temperatur Innen	: 37.50 °C
Temperatur Aussen	: 29.00 °C
Taupunkt		: 10.22 °C
Chill-Faktor		: 29.00 °C
Luftfeuchte Innen	: 20 %
Luftfeuchte Aussen	: 31 %
Windgeschwindkeit	: 1.77 km/h
max. Windgeschwindkeit	: 1.77 km/h
Windrichtung		: 261 °
Windrichtung		: W
Luftdruck absolut	: 984.42 hPa
Luftdruck relativ	: 1008.94 hPa
Regenrate		: 0 mm/h
Regenstatus		: kein Regen
Regen Tag		: 0 mm
Regen Woche		: 2.3 mm
Regen Monat		: 2.3 mm
Regen Jahr		: 0 mm
Sonnenstrahlung		: 45.51 W/m²
UV-Index		: 0
Zeitstempel		: 06.08.2020 19:54:26
Firmware		: EasyWeatherV1.5.2

Datenstring für ioBroker:
javascript.0.Wetterstation.Innentemperatur=37.50
&javascript.0.Wetterstation.Aussentemperatur=29.00
&javascript.0.Wetterstation.Taupunkt=10.22
&javascript.0.Wetterstation.Chillfaktor=29.00
&javascript.0.Wetterstation.Innenfeuchtigkeit=20
&javascript.0.Wetterstation.Aussenfeuchtigkeit=31
&javascript.0.Wetterstation.Wind=1.77
&javascript.0.Wetterstation.Wind_max=1.77
&javascript.0.Wetterstation.Windrichtung=261
&javascript.0.Wetterstation.Windrichtung_Text=W
&javascript.0.Wetterstation.Druck_absolut=984.42
&javascript.0.Wetterstation.Druck_relativ=1008.94
&javascript.0.Wetterstation.Regenrate=0
&javascript.0.Wetterstation.Regen_Tag=0
&javascript.0.Wetterstation.Regen_Woche=2.3
&javascript.0.Wetterstation.Regen_Monat=2.3
&javascript.0.Wetterstation.Regen_Jahr=0
&javascript.0.Wetterstation.Sonnenstrahlung=45.51
&javascript.0.Wetterstation.UV_Index=0&javascript.0.Wetterstation.Regenstatus=kein Regen&javascript.0.Wetterstation.UV_Belastung=keine&javascript.0.Wetterstation.Zeitstempel=06.08.2020 19:54:26

DATA von Wetterstation:
GET /weatherstation/updateweatherstation.php?ID=xxxxxx&PASSWORD=xxxxxx&indoortempf=99.5&tempf=84.2&dewptf=50.4&windchillf=84.2&indoorhumidity=20&humidity=31&windspeedmph=1.1&windgustmph=1.1&winddir=261&absbaromin=29.070&baromin=29.794&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.091&monthlyrainin=0.091&yearlyrainin=0&solarradiation=45.51&UV=0&dateutc=2020-08-06%2017:54:26&softwaretype=EasyWeatherV1.5.2&action=updateraw&realtime=1&rtfreq=5 HTTP/1.0

Debug VAR:
Installationsverzeichnis: /home/iobroker
IPP: 192.168.178.97:8087	WS_PORT: 1080		WS_POLL: 60		PRE_DP: javascript.0.Wetterstation
Script-Version: V1.3.0	Config-Version: V1.3.0	Sub-Version: V1.3.0

Falls ich noch was wegen der Fehlersuche tun, kann sag einfach bescheid. 

Freue mich über eine Rückmeldung. ;-)

VG Tom

**Comment by SBorg2014** [comment]
Hidiho,
sieht eigentlich alles gut aus. Die Firmware ist lt. Datenstring korrekt auf der Station. Wenn du erst heute das Update gefahren hast, wird es erst morgen angezeigt. Hintergrund ist einfach der, um die Systemlast zu minimieren und da sich die FW-Version nicht so häufig ändert, lese ich die nur 1x am Tag um Mitternacht von der Station aus.
...und wieder zur Minimierung der Systemlast wird nur geschrieben was sich auch wirklich ändert. Der "Sonnenschein" wurde von den Meteorologen auf >= 120Watt/m² definiert. Der Wert wird dann bei dir ~19.00 Uhr unterschritten + da er sich nicht ändert auch nicht im Datenpunkt aktualisiert (wäre ja der selbe Wert). Das betrifft aber nur Werte die ich errechne, nicht Direktwerte der Station. Die kommen immer 1:1 (bzw. metrisch umgerechnet ;-) ). 
Wenn morgen wieder mehr Sonne als 120W scheint werden sie wieder aktualisiert.

**Comment by fred0815** [comment]
Moin,
wow, das ja mal ne schnelle Antwort... vielen Dank für die Erklärung. Dann habe ich es jetzt auch verstanden... ;-)
Kannte den Wert der Sonnenschein Definition nicht. 
Hatte ich ganz vergessen zu erwähnen. Super tolles Skript, das du geschrieben hast.
VG Tom
