### ISSUE TITLE
Mehrere Wetterstationen

### ISSUE THREAD

**Issue by BenjaminK87** [SBorg2014/WLAN-Wetterstation#70]
Gibt es einen eleganten Weg mehrere Wetterstationen zeitgleich zu nutzen?

Oder eigenen Ordner mit eigenem Skript/Config erstellen und auch in ioBroker weiteren simpleAPI Adapter, etc?

**Comment by SBorg2014** [comment]
Ich sag mal Jein. Da das Skript einen eigenen Web-Server generiert und auf ein Datanpaket der Station lauscht, geht dies nur für eine Station.
Aber, wie du bereits vermutest, kannst du beliebig viele parallel laufen lassen. Der RAM-Bedarf liegt dabei unter 10MB, CPU-Last ist so gut wie nicht messbar. Du brauchst nichts weiter extra zu installieren, API etc. genügt eine Instanz. Die nimmt Daten auf Port xyz entgegen und schreibt die in den passenden Datenpunkt.
Du musst nur den Service anders nennen (zB. Wetterstation1, Wetter_Ost,...) und die sh, sub und conf in ein anderes Verzeichnis kopieren/installieren (daran denken, der neue Pfad muss auch im Service stehen). Da Intern auf den Namen zugegriffen wird __muss__ alles auch hier *wetterstation.\** heißen. Wenn es auf dem selben Rechner wie die Erste läuft, musst du natürlich für den Empfang einen anderen Port nutzen (Default 1080 [für die 1.], dann bspw. 1081 für die 2.). Der "Zugang" zum ioB (API, Port...) bleibt gleich. Bei der Konfiguration musst du nur einen anderen Datenpunktpfad wählen, also zB. `0_userdata.0.Wetterstation1` und dann auch in dem JS "wetterstation.js" den Part passend ändern:
 > let DP = "0_userdata.0.Wetterstation1.";
Wenn du mit InfluxDB loggst, wäre hier ein separates Bucket zu empfehlen, sonst kannst du die Werte nicht mehr unterscheiden. Überschrieben werden sie in der Regel nicht, da müssten sie schon auf die Nanosekunde genau gleich ankommen.
