### ISSUE TITLE
Log file?

### ISSUE THREAD

**Issue by bjoernbusch** [SBorg2014/WLAN-Wetterstation#9]
Ich habe alles erfolgreich eingerichtet und es kommt auch so ... 20 Minuten lang updates im iobroker an und nichts mehr. Wenn ich den Service dann neu starte läuft es wieder ca 20 Minuten.

Gibt es irgendwo ein LogFile in dem ich nach Fehlern suchen könnte oder wie kann ich dem auf den Grund gehen?

Mein iobroker läuft auf dem gleichen RaspberryPi wie das weatherstation.sh und ich habe es als system service eingerichtet.

**Comment by SBorg2014** [comment]
Den Fall gab es bisher noch nicht. Es könnte aber uU. (dafür spricht auch die begrenzte Laufzeit) auch der RAM des PI voll laufen. Log habe ich keines eingebaut, da es nach der Debug-Ausgabe bei jedem bisher lief/läuft und 99% des Quellcodes sich eh mit der Aufbereitung der Daten beschäftigt. Da wird ein ev. Fehler gleich im ioB geloggt ;)
Du kannst aber mal mittels ` ps -A|grep wetter*` nachschauen ob da zwei Instanzen nach dem Hänger noch laufen. Eine ist der eigentliche Service/Skript, die Andere ist die Netcat-Instanz, welche auf ein Datenpaket der Wetterstation wartet.
Mittels `htop` (sudo apt-get install htop) kannst du auch mal die Systemlast/Speicherverbrauch überprüfen. Sollte hier kaum noch RAM frei sein, könnte es daran liegen. Das Skript belegt zwar nur wenig RAM und in gleicher Größe, der ioB nimmt sich den RAM aber dynamisch. Hier könnte es zum testen mal genügen nicht benötigte Adapter temporär zu deaktivieren, wie bspw. BackIt-Up, die sowieso nur zu einer bestimmten Zeit laufen.
Im Zweifelsfall wäre das Auslagern des Skriptes auf einen anderen Rechner, sofern vorhanden, eine Option. Die Aufwändige, wenn alle Stricke reißen und kein Linux-Rechner zur Verfügung steht, wäre eine VM mittels zB. VirtualBox auf einer Windows-Maschine einzurichten.
...oder du versuchst dein Glück mit dem ioB-Adapter, da bin ich aber der falsche Ansprechpartner (und wird dir noch weniger helfen falls es ein RAM-Problem sein sollte, denn der braucht etliche MB an RAM, das Skript nur wenige kB).

**Comment by bjoernbusch** [comment]
@SBorg2014 Danke für die ausführlichen Tipps. Irgendwie läuft es jetzt. Ich habe den Service gestern Abend noch einmal neu gestartet und heute ist alles jedes mal up to date wenn ich reinschaue. Ich sehe mit grep 2 Instanzen und RAM ist noch genug frei. (Rpi4 mit 4GB Ram). Ich hab jetzt die RPi nochmal neu gestartet und werde das beobachten. Der Service kommt jedenfalls beim reboot wieder. Vielleicht war es auch nur ein Refresh Issue in der Objects Liste.

Alles gut, herzlichen Dank! Wo ist deine Kaffeekasse? Ich bin total begeistert, dass ich endlich diese Lösung gefunden habe. Ich wollte schon lang eine Wetterstation, konnte aber immer keine finden die vom Preis her ok ist und selbst bauen wollte ich nicht. Da war jetzt die Eurochron mit deiner Lösung die perfekte Lösung!
